#!/usr/bin/env python3
"""Generate frontend/src/nori/llm/prompts.generated.ts from the Python source of truth.

The hosted (LeLab-free) web build assembles the LLM request in the BROWSER and calls
Nori-Backend's generic /api/v1/agent/llm/messages proxy directly. To do that it needs the
same system prompts + tool schemas the LeLab server injects. Rather than hand-copy them
(drift), we generate a committed TS artifact from the single source of truth:

  - NORI_CODEGEN_SYSTEM / NORI_AGENT_SYSTEM  <- lelab/server.py   (module-level str consts)
  - AGENT_TOOLS                              <- frontend/packages/nori-sdk/robot-tools.json
                                                (itself generated from robot-ops.ts)

Run `npm run gen:llm-prompts` after editing either prompt in lelab/server.py. The output is
COMMITTED (like robot-tools.json) because the Vercel build is rooted at frontend/ and cannot
see lelab/ at build time. CI can re-run this and diff to catch drift.
"""

import ast
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SERVER_PY = REPO / "lelab" / "server.py"
TOOLS_JSON = REPO / "frontend" / "packages" / "nori-sdk" / "robot-tools.json"
OUT = REPO / "frontend" / "src" / "nori" / "llm" / "prompts.generated.ts"

WANT = {"NORI_CODEGEN_SYSTEM", "NORI_AGENT_SYSTEM"}


def extract_str_consts(py_path: Path, names: set[str]) -> dict[str, str]:
    """Return {name: value} for each module-level `NAME = "<str literal>"` assignment."""
    tree = ast.parse(py_path.read_text())
    found: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not (len(node.targets) == 1 and isinstance(node.targets[0], ast.Name)):
            continue
        name = node.targets[0].id
        if name in names and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            found[name] = node.value.value
    missing = names - found.keys()
    if missing:
        raise SystemExit(f"{py_path}: could not find str const(s): {sorted(missing)}")
    return found


def main() -> None:
    consts = extract_str_consts(SERVER_PY, WANT)
    tools = json.loads(TOOLS_JSON.read_text())["tools"]

    def emit(name: str, value) -> str:
        # JSON.stringify-compatible: json.dumps produces a valid TS string/array literal
        # with all escaping handled (backticks, ${}, newlines, quotes).
        return f"export const {name} = {json.dumps(value, ensure_ascii=False)} as const;\n\n"

    body = (
        "// GENERATED by frontend/scripts/gen_llm_prompts.py — DO NOT EDIT BY HAND.\n"
        "// Source of truth: lelab/server.py (prompts) + packages/nori-sdk/robot-tools.json (tools).\n"
        "// Regenerate with `npm run gen:llm-prompts`. Committed because the Vercel build is\n"
        "// rooted at frontend/ and cannot see lelab/ at build time.\n\n"
        + emit("NORI_CODEGEN_SYSTEM", consts["NORI_CODEGEN_SYSTEM"])
        + emit("NORI_AGENT_SYSTEM", consts["NORI_AGENT_SYSTEM"])
        + emit("AGENT_TOOLS", tools)
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(REPO)} "
          f"(codegen {len(consts['NORI_CODEGEN_SYSTEM'])} chars, "
          f"agent {len(consts['NORI_AGENT_SYSTEM'])} chars, {len(tools)} tools)")


if __name__ == "__main__":
    main()
