/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch Training */
        post: operations["dispatch_training_api_v1_training_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a safe pause of a running training job
         * @description Writes the job's S3 stop-flag; the container polls it (~20s) and
         *     pauses gracefully at the next poll + checkpoint. The job then lands in
         *     PAUSED with a resumable bundle (or COMPLETED, if it finished first —
         *     stop requests race the finish line by design).
         */
        post: operations["stop_training_job_api_v1_training_jobs__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/estimate-params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constants for client-side training-time estimates */
        get: operations["estimate_params_api_v1_training_estimate_params_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated customer's training jobs (newest first)
         * @description Returns every training job the customer has dispatched, in `created_at`
         *     descending order. No pagination in v1 — customers won't accumulate
         *     enough jobs to need it for a while; add `limit`/`cursor` params when
         *     they do.
         */
        get: operations["list_training_jobs_api_v1_training_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single training job by id (ownership-checked)
         * @description Returns one job by id. 404 if the job doesn't exist OR belongs to a
         *     different customer — same "no existence leak" pattern as the rest of
         *     the API.
         */
        get: operations["get_training_job_api_v1_training_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs/{job_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll training job logs (returns lines after `since`) */
        get: operations["get_training_job_logs_api_v1_training_jobs__job_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List policies available to the authenticated customer */
        get: operations["list_policies_api_v1_marketplace_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{listing_id}/acquire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire (install) a public marketplace listing for this customer */
        post: operations["acquire_policy_api_v1_marketplace_policies__listing_id__acquire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{ref}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the safetensors bytes for a policy the customer owns or has acquired */
        get: operations["download_policy_api_v1_marketplace_policies__ref__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full detail view for a policy the customer owns or can install */
        get: operations["policy_details_api_v1_marketplace_policies__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename your own trained policy (own policies only)
         * @description Set or clear the display title of an own-trained policy. The title is
         *     customer-visible once the policy is published to the community, so it is
         *     PII-scanned at write time with the same scanner the listing-creation tool
         *     uses (rejects absolute paths, emails, credentials, URLs, hub repo ids,
         *     robot serials). 404 if the ref isn't the caller's own renameable policy.
         */
        patch: operations["rename_policy_api_v1_marketplace_policies__ref__patch"];
        trace?: never;
    };
    "/api/v1/marketplace/policies/{ref}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the files that make up a policy (weights + configs + normalizers)
         * @description A policy is only runnable as a bundle (model.safetensors + config.json
         *     + pre/post-processor files). This returns the file list so the laptop can
         *     fetch each via /files/{name} and reconstruct the pretrained_model/ dir —
         *     the download-direction mirror of the dataset-upload manifest flow.
         *     HF locations stay internal — only names/sizes/hashes are exposed.
         */
        get: operations["get_policy_manifest_api_v1_marketplace_policies__ref__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{ref}/files/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one file of a policy bundle by its manifest name
         * @description Same entitlement rules as /download. `file_name` must be a name from
         *     /manifest (anything else 404s — there is no path interpretation). Bytes
         *     are verified against the promotion-time sha256 when one was recorded
         *     (pins the exact sanitized bytes); legacy files without a hash fall back
         *     to the same structural re-validation /download uses.
         */
        get: operations["download_policy_file_api_v1_marketplace_policies__ref__files__file_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{ref}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request community publication of your own trained policy
         * @description Creates a `community` listing in `pending_review` and queues the
         *     privacy re-homing copy (worker surface). NOT public yet — a human review
         *     approves after re-homing; poll GET /marketplace/my-listings for the
         *     outcome. 403 without an active `publish_public` consent; 409 for an
         *     already-active listing, an in-flight deletion, or a pre-bundle legacy
         *     policy; 404 if the ref isn't the caller's own promoted job.
         */
        post: operations["publish_policy_api_v1_marketplace_policies__ref__publish_post"];
        /**
         * Unpublish / retract your community listing for this policy
         * @description Instant, idempotent takedown: flips the active listing to `taken_down`
         *     (kept for audit) and revokes derived acquisitions. Empty `taken_down`
         *     means there was nothing active — still a success (idempotency).
         */
        delete: operations["unpublish_policy_api_v1_marketplace_policies__ref__publish_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/datasets/{upload_ref}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish one of your own datasets so others can train on it
         * @description Create a `dataset` community listing in `pending_review` and queue the
         *     re-homing copy (worker). Auto-publishes once re-homing + the format gate
         *     pass — open platform, no manual review. Source is one of your PROMOTED
         *     uploads (recorded locally, imported from HF, or captured onto Nori-cloud).
         *     403 without active `publish_public` consent; 409 for an already-active
         *     listing or in-flight deletion; 404 if the ref isn't your own promoted upload.
         */
        post: operations["publish_dataset_api_v1_marketplace_datasets__upload_ref__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/my-listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your community submissions and their review state
         * @description Every community listing the caller has submitted, all lifecycle states
         *     (pending_review / public / rejected / taken_down) — the owner-only view;
         *     the public catalog never shows non-public rows.
         */
        get: operations["my_listings_api_v1_marketplace_my_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/datasets/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the open datasets Nori publishes */
        get: operations["list_public_datasets_api_v1_marketplace_datasets_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision a new customer (first sign-in; no robot required)
         * @description First-sign-in provisioning. Creates:
         *       * customers row (auth_user_id, email, NULL robot_serial_number)
         *       * usage row (default allowance)
         *       * retention_policies row (schema defaults)
         *       * private HF dataset repo `NoriRobotics/customer-<short_uuid>`
         *
         *     Idempotent: re-calling for an already-provisioned auth user returns
         *     the existing customer's profile without modification (or re-create
         *     of the HF repo).
         */
        post: operations["provision_customer_api_v1_customers_me_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a robot serial number to the authenticated customer
         * @description Pair a robot to an already-provisioned customer (multi-robot).
         *
         *     Inserts a `robots` row. The customer's FIRST robot becomes active;
         *     subsequent robots are added inactive (use /robots/{serial}/select to
         *     switch). Idempotent if this customer already owns the serial. 409 only
         *     when the serial is already owned by ANOTHER customer (global UNIQUE).
         *
         *     The customers.robot_serial_number mirror tracks the ACTIVE robot, so
         *     is_paired / the laptop room key keep meaning "active robot".
         */
        post: operations["pair_robot_api_v1_customers_me_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/unpair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpair a robot (specific serial, or the active one if omitted)
         * @description Remove a robot from the customer. Pass a serial to unpair that specific
         *     robot; omit the body (or the serial) to unpair the active one. Idempotent:
         *     unpairing a serial the customer doesn't own is a no-op. If the removed
         *     robot was active, the most-recently-paired remaining robot is promoted so
         *     the customer keeps a usable default.
         */
        post: operations["unpair_robot_api_v1_customers_me_unpair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the customer's paired robots (active first)
         * @description Return all robots paired to the customer, active first then
         *     most-recently-paired.
         */
        get: operations["list_robots_api_v1_customers_me_robots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/robots/{serial}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set the customer's active robot
         * @description Make `serial` the customer's active robot (clears the previous active and
         *     updates the mirror). 404 if the customer doesn't own that serial
         *     (ownership-404 convention — don't reveal other customers' robots).
         */
        post: operations["select_robot_api_v1_customers_me_robots__serial__select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated customer's profile + provisioning state
         * @description Returns CustomerProfile if the auth user is provisioned, or
         *     NotProvisionedResponse if not. The laptop uses this to decide
         *     whether to route the user to the provisioning flow on sign-in.
         *
         *     Uses get_authenticated_user (JWT-only) rather than get_current_customer
         *     so that an un-provisioned user gets a clear 200 response rather than 401.
         */
        get: operations["get_me_api_v1_customers_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated customer's consents (active + revoked)
         * @description Returns all consents for the authenticated customer in granted_at
         *     descending order. Includes both active (revoked_at IS NULL) and
         *     historical revoked rows — the laptop's consent UI can filter either
         *     way client-side.
         */
        get: operations["list_consents_api_v1_consents_get"];
        put?: never;
        /**
         * Grant a consent for the authenticated customer
         * @description Insert a new active consents row for the (consent_type, scope) tuple.
         *
         *     Idempotent: if an active consent already exists matching
         *     (customer, consent_type, scope_dataset_repo), returns it unchanged
         *     rather than inserting a duplicate (which would violate the schema's
         *     partial unique index).
         *
         *     NOTE on policy_version bumps: if an active consent exists for the
         *     same (type, scope) but a *different* policy_version was supplied,
         *     we still return the existing row. To "re-agree" to a new ToS
         *     version, the client must explicitly revoke the old consent first
         *     and then grant a new one.
         */
        post: operations["grant_consent_api_v1_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consents/{consent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a consent (idempotent)
         * @description Set revoked_at = NOW() and optionally record a revocation reason.
         *     Idempotent: re-calling on an already-revoked consent returns the
         *     row unchanged.
         *
         *     Ownership-checked: 404 if the consent doesn't exist OR belongs to
         *     a different customer (no existence leak).
         */
        post: operations["revoke_consent_api_v1_consents__consent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated customer's promoted datasets (newest first)
         * @description Promoted upload sessions, newest first — the choices for the training
         *     form's dataset dropdown (`dataset_ref`). Only PROMOTED sessions have a
         *     trainable `hf_path_prefix`; PENDING/FAILED/CANCELLED are excluded.
         */
        get: operations["list_my_datasets_api_v1_datasets_upload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open an upload session and mint per-file presigned PUT URLs */
        post: operations["start_upload_api_v1_datasets_upload_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/{session_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify uploads (synchronous) + kick off the async commit to HF */
        post: operations["finalize_upload_api_v1_datasets_upload__session_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an upload session's current state */
        get: operations["get_upload_api_v1_datasets_upload__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a session before finalize (deletes S3 staging) */
        post: operations["cancel_upload_api_v1_datasets_upload__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deletion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * File a GDPR/CCPA right-to-erasure request
         * @description Insert a new PENDING deletion request for the authenticated customer.
         *
         *     Idempotent: if the customer already has an active (PENDING or
         *     IN_PROGRESS) request, returns that row unchanged rather than creating
         *     a duplicate. Matches the consents-grant pattern.
         *
         *     NOTE on scope mismatch: if an active request exists with a different
         *     `request_scope` than the new submission, we still return the existing
         *     row. The customer can't "upgrade" a data_only to a full via this
         *     endpoint — they'd need a cancel + re-request flow, which we don't
         *     expose in v1 (operator does it manually).
         */
        post: operations["create_deletion_request_api_v1_deletion_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the customer's current daily agent-token budget
         * @description Cheap, non-mutating budget read for the pre-turn gate and account UI.
         *     `hard_capped` true means no budget remains — the caller must not start a new
         *     turn. `soft_warning` true means past the soft threshold (still allowed).
         *     `hard_capped` also trips when the MONTHLY backstop is exhausted (013).
         */
        get: operations["get_agent_usage_api_v1_agent_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/usage/charge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record one turn's actual agent-token usage
         * @description Record a completed turn's real token counts and return the updated
         *     budget. Send a per-turn `turn_key` UUID for idempotent retries: the first
         *     charge with a key wins, replays return the current budget without
         *     double-counting. Without a key this is additive per call (legacy: one call
         *     == one turn, retry double-counts). The pre-turn gate (GET /agent/usage) is
         *     what enforces the cap; this endpoint always records, so a turn that
         *     overruns the cap is still billed (bounded to one turn).
         */
        post: operations["charge_agent_usage_api_v1_agent_usage_charge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/llm/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gated, metered Anthropic Messages proxy (non-streaming)
         * @description Gate → call Anthropic → charge → return the raw assistant turn. The response mirrors
         *     what LeLab returned before it forwarded: {stop_reason, content[], usage, budget}.
         */
        post: operations["llm_messages_api_v1_agent_llm_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/llm/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gated, metered Anthropic Messages proxy (streaming text)
         * @description Same gate, but streams the model's TEXT as `text/plain` chunks (what the codegen
         *     editor pipes to its buffer). We charge AFTER the stream completes, from the final
         *     message's usage — so a client that disconnects mid-stream simply isn't charged for
         *     that turn (bounded, fail-open). Errors before the stream opens (429/503) still raise
         *     normally; an Anthropic error mid-stream is emitted as a trailing comment because the
         *     200 headers are already sent.
         */
        post: operations["llm_messages_stream_api_v1_agent_llm_messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The customer's tier, monthly compute usage, and agent-token budgets */
        get: operations["billing_summary_api_v1_billing_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcquisitionResponse
         * @description Minimal acquisition record returned after a successful /acquire.
         *     Customer_id is implicit from the caller's auth context; not echoed back.
         */
        AcquisitionResponse: {
            /** Id */
            id: string;
            /** Listing Id */
            listing_id: string;
            /** Acquired At */
            acquired_at: string;
        };
        /** AgentBudget */
        AgentBudget: {
            /** Used Today */
            used_today: number;
            /** Allowed Today */
            allowed_today: number;
            /** Remaining Today */
            remaining_today: number;
            /** All Time Tokens */
            all_time_tokens: number;
            /** Soft Warn Threshold */
            soft_warn_threshold: number;
            /** Soft Warning */
            soft_warning: boolean;
            /** Hard Capped */
            hard_capped: boolean;
            /** Used Month */
            used_month?: number | null;
            /** Allowed Month */
            allowed_month?: number | null;
        };
        /** AgentChargeRequest */
        AgentChargeRequest: {
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Cache Read Tokens
             * @default 0
             */
            cache_read_tokens: number;
            /**
             * Cache Write Tokens
             * @default 0
             */
            cache_write_tokens: number;
            /**
             * New Run
             * @default false
             */
            new_run: boolean;
            /** Turn Key */
            turn_key?: string | null;
        };
        /** AgentTokensSummary */
        AgentTokensSummary: {
            /** Used Today */
            used_today: number;
            /** Allowed Today */
            allowed_today: number;
            /** Soft Warn Threshold */
            soft_warn_threshold: number;
            /** Used This Month */
            used_this_month?: number | null;
            /** Allowed Per Month */
            allowed_per_month?: number | null;
            /** Hard Capped */
            hard_capped: boolean;
        };
        /** BillingSummary */
        BillingSummary: {
            /** Billing Tier */
            billing_tier: string;
            /** Tier Price Usd Per Month */
            tier_price_usd_per_month: number | null;
            compute: components["schemas"]["ComputeSummary"];
            agent_tokens: components["schemas"]["AgentTokensSummary"];
            limits: components["schemas"]["TierLimitsSummary"] | null;
        };
        /** ComputeSummary */
        ComputeSummary: {
            /** Allowed Seconds Per Month */
            allowed_seconds_per_month: number;
            /** Consumed Seconds This Month */
            consumed_seconds_this_month: number;
            /** Reserved Seconds This Month */
            reserved_seconds_this_month: number;
            /** Remaining Seconds This Month */
            remaining_seconds_this_month: number;
        };
        /** Consent */
        Consent: {
            /** Id */
            id: string;
            /** Consent Type */
            consent_type: string;
            /** Scope Dataset Repo */
            scope_dataset_repo: string | null;
            /** Policy Version */
            policy_version: string;
            /** Granted At */
            granted_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Revocation Reason */
            revocation_reason: string | null;
        };
        /** ConsentGrantRequest */
        ConsentGrantRequest: {
            /**
             * Consent Type
             * @enum {string}
             */
            consent_type: "train_self" | "publish_public";
            /** Scope Dataset Repo */
            scope_dataset_repo?: string | null;
            /** Policy Version */
            policy_version: string;
        };
        /** ConsentRevokeRequest */
        ConsentRevokeRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * CustomerProfile
         * @description The shape returned by /provision, /pair, and /me. Stable contract
         *     for the laptop app.
         */
        CustomerProfile: {
            /** Id */
            id: string;
            /** Auth User Id */
            auth_user_id: string;
            /** Email */
            email: string | null;
            /** Billing Tier */
            billing_tier: string;
            /** Hf Dataset Repo */
            hf_dataset_repo: string;
            /** Robot Serial Number */
            robot_serial_number: string | null;
            /** Is Paired */
            is_paired: boolean;
            /** Allowed Seconds */
            allowed_seconds: number;
            /** Consumed Seconds */
            consumed_seconds: number;
            /** Remaining Seconds */
            remaining_seconds: number;
            /** Has Train Consent */
            has_train_consent: boolean;
            /** Has Active Deletion */
            has_active_deletion: boolean;
        };
        /**
         * DatasetEntry
         * @description One of the caller's promoted datasets, for the training dataset picker.
         *     `dataset_ref` is the promoted upload prefix passed back to
         *     POST /training/dispatch.
         */
        DatasetEntry: {
            /** Dataset Ref */
            dataset_ref: string;
            /** Label */
            label: string;
            /** Created At */
            created_at: string;
            /** Session Id */
            session_id: string;
        };
        /** DeletionRequest */
        DeletionRequest: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string;
            /** Request Scope */
            request_scope: string;
            /** Status */
            status: string;
            /** Notes */
            notes: string | null;
            /** Requested At */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DeletionRequestCreate */
        DeletionRequestCreate: {
            /**
             * Request Scope
             * @enum {string}
             */
            request_scope: "full" | "data_only";
            /** Notes */
            notes?: string | null;
        };
        /**
         * DispatchRequest
         * @description Laptop-forwarded training config. All fields optional with server
         *     defaults, so a bare `{}` (or a legacy `{timeout_seconds}`-only) body still
         *     dispatches. Security-critical flags (`push_to_hub`, cuda device, wandb) are
         *     NOT fields — they're forced server-side in the container script (§2).
         */
        DispatchRequest: {
            /**
             * Policy Type
             * @description Policy architecture to train. Whitelisted to detect.py classes.
             * @default act
             */
            policy_type: string;
            /**
             * Steps
             * @default 5000
             */
            steps: number;
            /**
             * Batch Size
             * @default 8
             */
            batch_size: number;
            /**
             * Num Workers
             * @default 4
             */
            num_workers: number;
            /** Seed */
            seed?: number | null;
            /**
             * Policy Use Amp
             * @default true
             */
            policy_use_amp: boolean;
            /**
             * Log Freq
             * @default 200
             */
            log_freq: number;
            /**
             * Timeout Seconds
             * @description Bounded per-job timeout. Clamped down by billing_tier.
             * @default 900
             */
            timeout_seconds: number;
            /**
             * Dataset Ref
             * @description A specific promoted upload prefix (uploads/<ts>/) in the caller's own repo. Default: the latest promoted upload.
             */
            dataset_ref?: string | null;
            /**
             * Open Dataset Id
             * @description Train on one of Nori's published open datasets instead of an own upload (id from GET /marketplace/datasets/public). Mutually exclusive with dataset_ref.
             */
            open_dataset_id?: string | null;
            /**
             * Resume From Job Id
             * @description Resume a PAUSED job of the caller's from its checkpoint bundle. The training config and dataset are taken from the paused job (they must match for lerobot resume); only timeout_seconds is fresh — it reserves a new usage segment (402 when the monthly allowance can't cover it).
             */
            resume_from_job_id?: string | null;
        };
        /** DispatchResponse */
        DispatchResponse: {
            /** Internal Job Uuid */
            internal_job_uuid: string;
            /** Hf Job Id */
            hf_job_id: string;
            /** Attribution Label */
            attribution_label: string;
            /** Reserved Seconds */
            reserved_seconds: number;
        };
        /**
         * EstimateParams
         * @description Constants the UI needs to show a live training-time estimate that can
         *     never disagree with the dispatch fit-gate (same numbers, same formula:
         *     seconds ≈ steps / rate, + setup_seconds on top, absorbed by the platform).
         *     Authenticated like every non-bootstrap surface; the values are not
         *     sensitive (derivable from any single job's logs) — the auth gate is just
         *     the house invariant.
         */
        EstimateParams: {
            /** Step Rates */
            step_rates: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Setup Seconds */
            setup_seconds: number;
            /** Max Timeout Seconds */
            max_timeout_seconds: number;
            /** Resumable */
            resumable: boolean;
        };
        /** FinalizeRequest */
        FinalizeRequest: {
            /** Commit Message */
            commit_message?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LlmMessagesRequest
         * @description A near-passthrough of the Anthropic Messages API. LeLab owns all prompt content;
         *     we add nothing but auth, budget, the key, and cache_control breakpoints (a cost knob,
         *     not content — see _add_cache_control).
         */
        LlmMessagesRequest: {
            /** Model */
            model: string;
            /** Max Tokens */
            max_tokens: number;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /** System */
            system?: string | null;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * New Run
             * @default false
             */
            new_run: boolean;
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /** MyListing */
        MyListing: {
            /** Listing Id */
            listing_id: string;
            /** Source Job Id */
            source_job_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Review Reason */
            review_reason?: string | null;
            /** In Review */
            in_review: boolean;
            /** Is Public */
            is_public: boolean;
            /** Created At */
            created_at: string;
        };
        /** PairRequest */
        PairRequest: {
            /** Robot Serial Number */
            robot_serial_number: string;
            /** Nickname */
            nickname?: string | null;
        };
        /**
         * PolicyDetails
         * @description Full detail view — superset of the catalog list entry. `editable` is
         *     true only for the caller's own policies (they may PATCH the title).
         *     Provenance fields (dataset_repo, final_cost_usd, timeout_seconds,
         *     promoted_at) are populated for own policies, null for listings.
         */
        PolicyDetails: {
            /** Ref */
            ref: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Is Renamed */
            is_renamed: boolean;
            /** Description */
            description?: string | null;
            /** Policy Class */
            policy_class?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Created At */
            created_at: string;
            /** Dataset Repo */
            dataset_repo?: string | null;
            /** Promoted At */
            promoted_at?: string | null;
            /** Final Cost Usd */
            final_cost_usd?: number | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Editable */
            editable: boolean;
            /** Files */
            files: components["schemas"]["PolicyFileSummary"][];
        };
        /**
         * PolicyFileEntry
         * @description One file of a policy bundle. `name` is the exact filename to place in
         *     a local pretrained_model/ directory; fetch its bytes from
         *     GET /policies/{ref}/files/{name}. size/sha256 are null on legacy
         *     single-file promotions (no manifest recorded).
         */
        PolicyFileEntry: {
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Sha256 */
            sha256?: string | null;
        };
        /** PolicyFileSummary */
        PolicyFileSummary: {
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Sha256 */
            sha256?: string | null;
        };
        /**
         * PolicyListEntry
         * @description One row in the merged catalog. `ref` is the opaque UUID the client
         *     passes back to /download — could be a jobs.id or marketplace_listings.id;
         *     the backend resolves which internally.
         */
        PolicyListEntry: {
            /** Ref */
            ref: string;
            /** Source */
            source: string;
            /**
             * Kind
             * @default policy
             */
            kind: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Policy Class */
            policy_class?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Linked Dataset Listing Id */
            linked_dataset_listing_id?: string | null;
            /** Created At */
            created_at: string;
        };
        /** PolicyManifest */
        PolicyManifest: {
            /** Files */
            files: components["schemas"]["PolicyFileEntry"][];
        };
        /** ProvisionRequest */
        ProvisionRequest: Record<string, never>;
        /** PublicDatasetEntry */
        PublicDatasetEntry: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Hf Repo */
            hf_repo: string;
            /** License */
            license?: string | null;
        };
        /**
         * PublishRequest
         * @description Publish-request text — customer-visible on the public catalog once
         *     approved, so PII-scanned at write time (same scanner as rename/listing
         *     creation).
         */
        PublishRequest: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
        };
        /** RenameRequest */
        RenameRequest: {
            /** Title */
            title?: string | null;
        };
        /**
         * Robot
         * @description One paired robot. Returned by GET /customers/me/robots.
         */
        Robot: {
            /** Robot Serial Number */
            robot_serial_number: string;
            /** Nickname */
            nickname?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Paired At */
            paired_at: string;
        };
        /**
         * SessionRow
         * @description Mirrors the dataset_upload_sessions row. Used for status + finalize +
         *     cancel responses. Schema-faithful (no field reshaping); laptop reads
         *     `status` to drive its state machine.
         */
        SessionRow: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            }[];
            /** Commit Message */
            commit_message?: string | null;
            /** S3 Prefix */
            s3_prefix: string;
            /** Hf Path Prefix */
            hf_path_prefix?: string | null;
            /** Hf Commit Sha */
            hf_commit_sha?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Finalized At */
            finalized_at?: string | null;
        };
        /** StartRequest */
        StartRequest: {
            /** Manifest */
            manifest: components["schemas"]["ManifestEntry"][];
            /** Commit Message */
            commit_message?: string | null;
        };
        /** StartResponse */
        StartResponse: {
            /** Session Id */
            session_id: string;
            /** Uploads */
            uploads: components["schemas"]["UploadEntry"][];
            /** Expires At */
            expires_at: string;
        };
        /** StopResponse */
        StopResponse: {
            /** Stopping */
            stopping: boolean;
            /** Detail */
            detail: string;
        };
        /** TierLimitsSummary */
        TierLimitsSummary: {
            /** Max Job Timeout Seconds */
            max_job_timeout_seconds: number;
            /** Max Concurrent Jobs */
            max_concurrent_jobs: number;
            /** Max Robots */
            max_robots: number;
        };
        /** TrainingJob */
        TrainingJob: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Dataset Repo */
            dataset_repo: string;
            /** Timeout Duration Seconds */
            timeout_duration_seconds: number;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /** Final Cost Usd */
            final_cost_usd?: number | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Resulting Checkpoint Url */
            resulting_checkpoint_url?: string | null;
            /** Artifact Promoted At */
            artifact_promoted_at?: string | null;
            /** Applied Config */
            applied_config?: {
                [key: string]: unknown;
            } | null;
            /** Steps Done */
            steps_done?: number | null;
            /** Run Started At */
            run_started_at?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * TrainingJobLogs
         * @description Poll response shape for `/jobs/{id}/logs?since=N`.
         *
         *     `lines` are the lines from `since` onward (no trailing newlines).
         *     Client should pass back `next_offset` on the next poll. When
         *     `is_terminal=true`, the client should stop polling — no more logs
         *     will arrive.
         */
        TrainingJobLogs: {
            /** Lines */
            lines: string[];
            /** Next Offset */
            next_offset: number;
            /** Job Status */
            job_status: string;
            /** Is Terminal */
            is_terminal: boolean;
        };
        /** UnpairRequest */
        UnpairRequest: {
            /** Robot Serial Number */
            robot_serial_number?: string | null;
        };
        /** UnpublishResponse */
        UnpublishResponse: {
            /** Taken Down */
            taken_down: string[];
        };
        /** UploadEntry */
        UploadEntry: {
            /** Path */
            path: string;
            /** Put Url */
            put_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dispatch_training_api_v1_training_dispatch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_training_job_api_v1_training_jobs__job_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_params_api_v1_training_estimate_params_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateParams"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_training_jobs_api_v1_training_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_job_api_v1_training_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_job_logs_api_v1_training_jobs__job_id__logs_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobLogs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_v1_marketplace_policies_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_policy_api_v1_marketplace_policies__listing_id__acquire_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_policy_api_v1_marketplace_policies__ref__download_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_details_api_v1_marketplace_policies__ref__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_policy_api_v1_marketplace_policies__ref__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_manifest_api_v1_marketplace_policies__ref__manifest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_policy_file_api_v1_marketplace_policies__ref__files__file_name__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_policy_api_v1_marketplace_policies__ref__publish_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_policy_api_v1_marketplace_policies__ref__publish_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnpublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dataset_api_v1_marketplace_datasets__upload_ref__publish_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                upload_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_listings_api_v1_marketplace_my_listings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyListing"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_datasets_api_v1_marketplace_datasets_public_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDatasetEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_customer_api_v1_customers_me_provision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProvisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_robot_api_v1_customers_me_pair_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpair_robot_api_v1_customers_me_unpair_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UnpairRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_robots_api_v1_customers_me_robots_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Robot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_robot_api_v1_customers_me_robots__serial__select_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_customers_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consents_api_v1_consents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_consent_api_v1_consents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_consent_api_v1_consents__consent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConsentRevokeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_datasets_api_v1_datasets_upload_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_upload_api_v1_datasets_upload_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_api_v1_datasets_upload__session_id__finalize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinalizeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_api_v1_datasets_upload__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_upload_api_v1_datasets_upload__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deletion_request_api_v1_deletion_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletionRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_usage_api_v1_agent_usage_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_agent_usage_api_v1_agent_usage_charge_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChargeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBudget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_messages_api_v1_agent_llm_messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmMessagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_messages_stream_api_v1_agent_llm_messages_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmMessagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    billing_summary_api_v1_billing_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
