/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch Training */
        post: operations["dispatch_training_api_v1_training_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated customer's training jobs (newest first)
         * @description Returns every training job the customer has dispatched, in `created_at`
         *     descending order. No pagination in v1 — customers won't accumulate
         *     enough jobs to need it for a while; add `limit`/`cursor` params when
         *     they do.
         */
        get: operations["list_training_jobs_api_v1_training_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single training job by id (ownership-checked)
         * @description Returns one job by id. 404 if the job doesn't exist OR belongs to a
         *     different customer — same "no existence leak" pattern as the rest of
         *     the API.
         */
        get: operations["get_training_job_api_v1_training_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training/jobs/{job_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll training job logs (returns lines after `since`) */
        get: operations["get_training_job_logs_api_v1_training_jobs__job_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List policies available to the authenticated customer */
        get: operations["list_policies_api_v1_marketplace_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{listing_id}/acquire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire (install) a public marketplace listing for this customer */
        post: operations["acquire_policy_api_v1_marketplace_policies__listing_id__acquire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/policies/{ref}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the safetensors bytes for a policy the customer owns or has acquired */
        get: operations["download_policy_api_v1_marketplace_policies__ref__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/datasets/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the open datasets Nori publishes */
        get: operations["list_public_datasets_api_v1_marketplace_datasets_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision a new customer (first sign-in; no robot required)
         * @description First-sign-in provisioning. Creates:
         *       * customers row (auth_user_id, email, NULL robot_serial_number)
         *       * usage row (default allowance)
         *       * retention_policies row (schema defaults)
         *       * private HF dataset repo `Nori-Test-Org/customer-<short_uuid>`
         *
         *     Idempotent: re-calling for an already-provisioned auth user returns
         *     the existing customer's profile without modification (or re-create
         *     of the HF repo).
         */
        post: operations["provision_customer_api_v1_customers_me_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a robot serial number to the authenticated customer
         * @description Attach a robot serial to an already-provisioned customer. Separate from
         *     /provision so that beta customers can sign in before their robots ship.
         *
         *     Idempotent if the serial matches the existing one. Fails 409 if the
         *     customer is already paired to a DIFFERENT serial (explicit re-pair must
         *     use a separate flow — not in v1).
         */
        post: operations["pair_robot_api_v1_customers_me_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated customer's profile + provisioning state
         * @description Returns CustomerProfile if the auth user is provisioned, or
         *     NotProvisionedResponse if not. The laptop uses this to decide
         *     whether to route the user to the provisioning flow on sign-in.
         *
         *     Uses get_authenticated_user (JWT-only) rather than get_current_customer
         *     so that an un-provisioned user gets a clear 200 response rather than 401.
         */
        get: operations["get_me_api_v1_customers_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated customer's consents (active + revoked)
         * @description Returns all consents for the authenticated customer in granted_at
         *     descending order. Includes both active (revoked_at IS NULL) and
         *     historical revoked rows — the laptop's consent UI can filter either
         *     way client-side.
         */
        get: operations["list_consents_api_v1_consents_get"];
        put?: never;
        /**
         * Grant a consent for the authenticated customer
         * @description Insert a new active consents row for the (consent_type, scope) tuple.
         *
         *     Idempotent: if an active consent already exists matching
         *     (customer, consent_type, scope_dataset_repo), returns it unchanged
         *     rather than inserting a duplicate (which would violate the schema's
         *     partial unique index).
         *
         *     NOTE on policy_version bumps: if an active consent exists for the
         *     same (type, scope) but a *different* policy_version was supplied,
         *     we still return the existing row. To "re-agree" to a new ToS
         *     version, the client must explicitly revoke the old consent first
         *     and then grant a new one.
         */
        post: operations["grant_consent_api_v1_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consents/{consent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a consent (idempotent)
         * @description Set revoked_at = NOW() and optionally record a revocation reason.
         *     Idempotent: re-calling on an already-revoked consent returns the
         *     row unchanged.
         *
         *     Ownership-checked: 404 if the consent doesn't exist OR belongs to
         *     a different customer (no existence leak).
         */
        post: operations["revoke_consent_api_v1_consents__consent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open an upload session and mint per-file presigned PUT URLs */
        post: operations["start_upload_api_v1_datasets_upload_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/{session_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate uploaded payload + commit to the customer's HF dataset repo */
        post: operations["finalize_upload_api_v1_datasets_upload__session_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an upload session's current state */
        get: operations["get_upload_api_v1_datasets_upload__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a session before finalize (deletes S3 staging) */
        post: operations["cancel_upload_api_v1_datasets_upload__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deletion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * File a GDPR/CCPA right-to-erasure request
         * @description Insert a new PENDING deletion request for the authenticated customer.
         *
         *     Idempotent: if the customer already has an active (PENDING or
         *     IN_PROGRESS) request, returns that row unchanged rather than creating
         *     a duplicate. Matches the consents-grant pattern.
         *
         *     NOTE on scope mismatch: if an active request exists with a different
         *     `request_scope` than the new submission, we still return the existing
         *     row. The customer can't "upgrade" a data_only to a full via this
         *     endpoint — they'd need a cancel + re-request flow, which we don't
         *     expose in v1 (operator does it manually).
         */
        post: operations["create_deletion_request_api_v1_deletion_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcquisitionResponse
         * @description Minimal acquisition record returned after a successful /acquire.
         *     Customer_id is implicit from the caller's auth context; not echoed back.
         */
        AcquisitionResponse: {
            /** Id */
            id: string;
            /** Listing Id */
            listing_id: string;
            /** Acquired At */
            acquired_at: string;
        };
        /** Consent */
        Consent: {
            /** Id */
            id: string;
            /** Consent Type */
            consent_type: string;
            /** Scope Dataset Repo */
            scope_dataset_repo: string | null;
            /** Policy Version */
            policy_version: string;
            /** Granted At */
            granted_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Revocation Reason */
            revocation_reason: string | null;
        };
        /** ConsentGrantRequest */
        ConsentGrantRequest: {
            /**
             * Consent Type
             * @enum {string}
             */
            consent_type: "train_self" | "publish_public";
            /** Scope Dataset Repo */
            scope_dataset_repo?: string | null;
            /** Policy Version */
            policy_version: string;
        };
        /** ConsentRevokeRequest */
        ConsentRevokeRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * CustomerProfile
         * @description The shape returned by /provision, /pair, and /me. Stable contract
         *     for the laptop app.
         */
        CustomerProfile: {
            /** Id */
            id: string;
            /** Auth User Id */
            auth_user_id: string;
            /** Email */
            email: string | null;
            /** Billing Tier */
            billing_tier: string;
            /** Hf Dataset Repo */
            hf_dataset_repo: string;
            /** Robot Serial Number */
            robot_serial_number: string | null;
            /** Is Paired */
            is_paired: boolean;
            /** Allowed Seconds */
            allowed_seconds: number;
            /** Consumed Seconds */
            consumed_seconds: number;
            /** Remaining Seconds */
            remaining_seconds: number;
            /** Has Train Consent */
            has_train_consent: boolean;
            /** Has Active Deletion */
            has_active_deletion: boolean;
        };
        /** DeletionRequest */
        DeletionRequest: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string;
            /** Request Scope */
            request_scope: string;
            /** Status */
            status: string;
            /** Notes */
            notes: string | null;
            /** Requested At */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DeletionRequestCreate */
        DeletionRequestCreate: {
            /**
             * Request Scope
             * @enum {string}
             */
            request_scope: "full" | "data_only";
            /** Notes */
            notes?: string | null;
        };
        /** DispatchRequest */
        DispatchRequest: {
            /**
             * Timeout Seconds
             * @description Bounded per-job timeout. Production: clamp by billing_tier.
             * @default 900
             */
            timeout_seconds: number;
        };
        /** DispatchResponse */
        DispatchResponse: {
            /** Internal Job Uuid */
            internal_job_uuid: string;
            /** Hf Job Id */
            hf_job_id: string;
            /** Attribution Label */
            attribution_label: string;
            /** Reserved Seconds */
            reserved_seconds: number;
        };
        /** FinalizeRequest */
        FinalizeRequest: {
            /** Commit Message */
            commit_message?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /** PairRequest */
        PairRequest: {
            /** Robot Serial Number */
            robot_serial_number: string;
        };
        /**
         * PolicyListEntry
         * @description One row in the merged catalog. `ref` is the opaque UUID the client
         *     passes back to /download — could be a jobs.id or marketplace_listings.id;
         *     the backend resolves which internally.
         */
        PolicyListEntry: {
            /** Ref */
            ref: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Policy Class */
            policy_class?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Created At */
            created_at: string;
        };
        /** ProvisionRequest */
        ProvisionRequest: Record<string, never>;
        /** PublicDatasetEntry */
        PublicDatasetEntry: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Hf Repo */
            hf_repo: string;
            /** License */
            license?: string | null;
        };
        /**
         * SessionRow
         * @description Mirrors the dataset_upload_sessions row. Used for status + finalize +
         *     cancel responses. Schema-faithful (no field reshaping); laptop reads
         *     `status` to drive its state machine.
         */
        SessionRow: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            }[];
            /** Commit Message */
            commit_message?: string | null;
            /** S3 Prefix */
            s3_prefix: string;
            /** Hf Path Prefix */
            hf_path_prefix?: string | null;
            /** Hf Commit Sha */
            hf_commit_sha?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Finalized At */
            finalized_at?: string | null;
        };
        /** StartRequest */
        StartRequest: {
            /** Manifest */
            manifest: components["schemas"]["ManifestEntry"][];
            /** Commit Message */
            commit_message?: string | null;
        };
        /** StartResponse */
        StartResponse: {
            /** Session Id */
            session_id: string;
            /** Uploads */
            uploads: components["schemas"]["UploadEntry"][];
            /** Expires At */
            expires_at: string;
        };
        /** TrainingJob */
        TrainingJob: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Dataset Repo */
            dataset_repo: string;
            /** Timeout Duration Seconds */
            timeout_duration_seconds: number;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /** Final Cost Usd */
            final_cost_usd?: number | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Resulting Checkpoint Url */
            resulting_checkpoint_url?: string | null;
            /** Artifact Promoted At */
            artifact_promoted_at?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * TrainingJobLogs
         * @description Poll response shape for `/jobs/{id}/logs?since=N`.
         *
         *     `lines` are the lines from `since` onward (no trailing newlines).
         *     Client should pass back `next_offset` on the next poll. When
         *     `is_terminal=true`, the client should stop polling — no more logs
         *     will arrive.
         */
        TrainingJobLogs: {
            /** Lines */
            lines: string[];
            /** Next Offset */
            next_offset: number;
            /** Job Status */
            job_status: string;
            /** Is Terminal */
            is_terminal: boolean;
        };
        /** UploadEntry */
        UploadEntry: {
            /** Path */
            path: string;
            /** Put Url */
            put_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dispatch_training_api_v1_training_dispatch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_training_jobs_api_v1_training_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_job_api_v1_training_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_job_logs_api_v1_training_jobs__job_id__logs_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobLogs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_v1_marketplace_policies_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_policy_api_v1_marketplace_policies__listing_id__acquire_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_policy_api_v1_marketplace_policies__ref__download_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_datasets_api_v1_marketplace_datasets_public_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDatasetEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_customer_api_v1_customers_me_provision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProvisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_robot_api_v1_customers_me_pair_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_customers_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consents_api_v1_consents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_consent_api_v1_consents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_consent_api_v1_consents__consent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConsentRevokeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_upload_api_v1_datasets_upload_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_api_v1_datasets_upload__session_id__finalize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinalizeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_api_v1_datasets_upload__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_upload_api_v1_datasets_upload__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deletion_request_api_v1_deletion_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletionRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
