// NORI: Additive. The TS arm solver against the Python original as ORACLE.
//
// arm-kinematics.ts is a 1:1 port of nori_gateway/arm_kinematics.py (branch
// vr-arm-kinematics, b2dcb56), which is the version that was derived, reviewed
// and tested against the URDF. Re-deriving tests for the port would only prove
// the port agrees with itself. So the vectors in armKinematicsOracle.json were
// GENERATED BY THAT PYTHON and are asserted here — if the port drifts, or if
// someone "fixes" a sign, this fails.
//
// Tolerances are tight on purpose: this is the same arithmetic in a different
// language, not an approximation of it. Doubles either agree to ~1e-12 or the
// port is wrong.
import { describe, it, expect } from "vitest";
import {
  wristPoint, elbowPoint, solveWristPoint, swivelOf, jointDistance,
  shoulderPoint, UPPER_ARM_M, FOREARM_M, SwivelTracker,
  type ArmQ, type Vec3,
} from "@nori/sdk/vr";
import ORACLE from "./armKinematicsOracle.json";

type FkRow = { q: number[]; sign: number; wrist: number[]; elbow: number[] };
type IkRow = { target: number[]; swivel: number; seed: number[] | null; sign: number; q: number[] | null };
type SwRow = { q: number[]; sign: number; swivel: number };

const TOL = 1e-12;
const v3 = (a: number[]) => a as Vec3;
const q4 = (a: number[]) => a as ArmQ;

describe("forward kinematics matches the Python oracle", () => {
  it("wrist point, both arms", () => {
    let worst = 0;
    for (const r of ORACLE.fk as FkRow[]) {
      const got = wristPoint(r.q[0], r.q[1], r.q[2], r.q[3], r.sign);
      for (let i = 0; i < 3; i++) worst = Math.max(worst, Math.abs(got[i] - r.wrist[i]));
    }
    expect(worst).toBeLessThan(TOL);
  });

  it("elbow point, both arms", () => {
    let worst = 0;
    for (const r of ORACLE.fk as FkRow[]) {
      const got = elbowPoint(r.q[0], r.q[1], r.sign);
      for (let i = 0; i < 3; i++) worst = Math.max(worst, Math.abs(got[i] - r.elbow[i]));
    }
    expect(worst).toBeLessThan(TOL);
  });

  it("swivel_of, both arms", () => {
    let worst = 0;
    for (const r of ORACLE.swivel_of as SwRow[]) {
      worst = Math.max(worst, Math.abs(swivelOf(q4(r.q), r.sign) - r.swivel));
    }
    expect(worst).toBeLessThan(1e-9);
  });
});

describe("inverse kinematics matches the Python oracle", () => {
  it("agrees on every solution AND every refusal", () => {
    let worst = 0, solved = 0, refused = 0;
    for (const r of ORACLE.ik as IkRow[]) {
      const got = solveWristPoint(
        v3(r.target), r.swivel, r.seed ? q4(r.seed) : null, r.sign);
      if (r.q === null) {
        // Refusals matter as much as solutions: a port that solves something
        // the original refused is out of the joint limits.
        expect(got).toBeNull();
        refused++;
        continue;
      }
      expect(got).not.toBeNull();
      for (let i = 0; i < 4; i++) worst = Math.max(worst, Math.abs(got![i] - r.q[i]));
      solved++;
    }
    expect(solved).toBeGreaterThan(250);
    expect(refused).toBeGreaterThan(0);
    expect(worst).toBeLessThan(TOL);
  });

  it("round-trips: solving a target then FK returns the target", () => {
    // Independent of the oracle — this checks the solver against GEOMETRY.
    let worst = 0;
    for (const r of (ORACLE.ik as IkRow[]).filter((x) => x.q)) {
      const got = solveWristPoint(v3(r.target), r.swivel, r.seed ? q4(r.seed) : null, r.sign)!;
      const back = wristPoint(got[0], got[1], got[2], got[3], r.sign);
      for (let i = 0; i < 3; i++) worst = Math.max(worst, Math.abs(back[i] - r.target[i]));
    }
    expect(worst).toBeLessThan(1e-9);
  });
});

describe("geometry invariants", () => {
  it("the shoulder is spherical — bicep_yaw does not move the elbow", () => {
    // The property the whole wrist-point decomposition rests on.
    const a = elbowPoint(0.4, 0.9, 1);
    for (const q3 of [-2, -0.5, 0, 1.1, 3]) {
      const w = wristPoint(0.4, 0.9, q3, 0.0, 1); // q4 = 0 -> wrist on the upper-arm axis
      expect(Number.isFinite(w[0])).toBe(true);
    }
    expect(elbowPoint(0.4, 0.9, 1)).toEqual(a);
  });

  it("max reach is the sum of the two links", () => {
    const S = shoulderPoint(1);
    const q = solveWristPoint([S[0], S[1], S[2] - (UPPER_ARM_M + FOREARM_M) + 1e-9], 0, null, 1);
    expect(q).not.toBeNull();
    expect(UPPER_ARM_M + FOREARM_M).toBeCloseTo(0.34356, 5);
  });

  it("jointDistance is unwrapped — a joint cannot take the short way round", () => {
    // shoulder_pitch and bicep_yaw are limited to exactly +/-pi. Measuring this
    // with a wrap let a 6.2 rad sweep through the continuity ceiling on hardware.
    expect(jointDistance([-3.1, 0, 0, 0], [3.1, 0, 0, 0])).toBeCloseTo(6.2, 9);
  });

  it("the two shoulders are Y-mirrored and the arms have equal reach", () => {
    // NOT "the same q gives mirrored points": it does not. shoulderDir negates
    // all three components under `sign`, so the mirror of a left configuration
    // is q1 + pi, not q1. Asserting the naive version failed here by 0.20 m and
    // that failure was the test being wrong, not the port. What IS true by
    // construction is that the mounts mirror in Y and the links are identical.
    const L = shoulderPoint(1), R = shoulderPoint(-1);
    expect(Math.abs(L[0] - R[0])).toBeLessThan(1e-15);
    expect(Math.abs(L[1] + R[1])).toBeLessThan(1e-15);
    expect(Math.abs(L[2] - R[2])).toBeLessThan(1e-15);
    // Same links both sides, so the same target offset from each shoulder is
    // reachable on both — the property the mapper actually relies on.
    for (const sign of [1, -1]) {
      const S = shoulderPoint(sign);
      const t: Vec3 = [S[0], S[1], S[2] - 0.30];
      expect(solveWristPoint(t, 0, null, sign)).not.toBeNull();
    }
  });
});

describe("SwivelTracker", () => {
  it("refuses a step it cannot take smoothly and reports the offender", () => {
    const t = new SwivelTracker(0, 1);
    const S = shoulderPoint(1);
    const near: Vec3 = [S[0] + 0.1, S[1], S[2] - 0.25];
    const first = t.solve(near, 0, 0.02, null);
    expect(first).not.toBeNull();
    // A tiny dt makes the ceiling tiny, so any real motion is refused.
    const far: Vec3 = [S[0] - 0.2, S[1] + 0.15, S[2] - 0.1];
    const r = t.solve(far, 3.0, 1e-6, first!.q);
    if (r === null) expect(typeof t.blockedBy === "number" || t.blockedBy === null).toBe(true);
  });

  it("latches its swivel across ticks", () => {
    const t = new SwivelTracker(0.3, 1);
    const S = shoulderPoint(1);
    const tgt: Vec3 = [S[0] + 0.05, S[1] + 0.05, S[2] - 0.28];
    const r = t.solve(tgt, 0.3, 0.02, null);
    if (r) expect(t.value).toBeCloseTo(r.swivel, 12);
  });
});
