import React, { useContext, useEffect, useRef, useState } from "react";
import * as THREE from "three";

import URDFManipulator from "urdf-loader/src/urdf-manipulator-element.js";
import {
  createUrdfViewer,
  setupMeshLoader,
  URDFViewerElement,
} from "@/lib/urdfViewerHelpers";
import { ThemeProviderContext } from "@/contexts/ThemeContext";
import { cn } from "@/lib/utils";

if (typeof window !== "undefined" && !customElements.get("urdf-viewer")) {
  customElements.define("urdf-viewer", URDFManipulator);
}

/**
 * Renders the real Nori robot description.
 *
 * Deliberately NOT the upstream `UrdfViewer`: that one is bound to LeLab's
 * drag-and-drop context, defaults to the SO-101 arm, and opens a websocket for
 * live joint streaming. None of that applies to showing one fixed, shipped model.
 *
 * Presentation is matched to `nori/remote/Robot3D` (the stylised model on the
 * remote page) so the two read as the same robot: same palette, same lighting,
 * same long-lens low-angle framing. The palette below mirrors the constants in
 * packages/nori-sdk/src/robot-model.ts — if those change, change these.
 *
 * Assets are static files under `public/nori-urdf/`, generated by
 * `nori_ws/urdf_release/tools/sync_to_lelab.py`. Re-run it when the model changes.
 */

const URDF_PATH = "/nori-urdf/nori.urdf";

const HIGHLIGHT = "#a1d873"; // ARM_ACTIVE — the green a selected arm turns on the remote page

/**
 * Surface finish, from the description's own `materials.yaml` — the team's
 * render-validated PBR values (roughness / metallic per link), shipped alongside
 * the model as `materials.json` by sync_to_lelab.py.
 *
 * URDF carries colour and nothing else, so without this the viewer has to invent
 * surface properties. Colour still comes from the URDF <material> elements: those
 * include the stylised standin palette (white head, caps) that materials.yaml has
 * no opinion on, since it only describes the two real robot finishes.
 */
type Finish = { roughness: number; metalness: number };
const DEFAULT_FINISH: Finish = { roughness: 0.78, metalness: 0.06 };

type MaterialsDoc = {
  materials?: Record<string, { roughness?: number; metallic?: number }>;
  assign?: Record<string, string>;
};

/**
 * Per-link overrides applied ON TOP of materials.yaml.
 *
 * TEMPORARY. materials.yaml still describes the lift as foam-covered
 * (body_mat, roughness 0.9, metallic 0.0), which is stale — the lift is bare
 * metal now. The fix belongs in materials.yaml itself, since that file also feeds
 * the SDG renderer; this only stops the viewer showing something we know is wrong
 * in the meantime. DELETE THIS once materials.yaml is corrected.
 */
/**
 * Finishes keyed by URDF MATERIAL name, checked before anything link-based.
 *
 * materials.yaml binds finishes per link, which cannot express a link carrying
 * several surfaces — head_link alone is white shell, glass screen and lit eyes.
 * Material name is the finer-grained key, so it wins.
 */
const MATERIAL_FINISHES: Record<string, Finish> = {
  nori_screen: { roughness: 0.08, metalness: 0.85 }, // glossy display glass
  nori_eye: { roughness: 0.25, metalness: 0.1 },
};

const FINISH_OVERRIDES: Record<string, Finish> = {
  lift_bottom_link: { roughness: 0.24, metalness: 0.92 },
  lift_middle_link: { roughness: 0.24, metalness: 0.92 },
  lift_top_link: { roughness: 0.24, metalness: 0.92 },
};

function buildFinishLookup(
  doc: MaterialsDoc | null
): (link: string, material: string) => Finish {
  if (!doc?.materials || !doc?.assign)
    return (link: string, material: string) =>
      MATERIAL_FINISHES[material] ?? FINISH_OVERRIDES[link] ?? DEFAULT_FINISH;
  const finishFor = (matName: string | undefined): Finish => {
    const m = matName ? doc.materials?.[matName] : undefined;
    return m
      ? { roughness: m.roughness ?? DEFAULT_FINISH.roughness, metalness: m.metallic ?? 0 }
      : DEFAULT_FINISH;
  };
  const fallback = finishFor(doc.assign.default);
  return (link: string, material: string) =>
    MATERIAL_FINISHES[material] ??
    FINISH_OVERRIDES[link] ??
    (doc.assign?.[link] ? finishFor(doc.assign[link]) : fallback);
}

/**
 * The URDF addresses meshes as `package://nori_description/meshes/...`, a ROS
 * convention the browser knows nothing about. Rewrite to the static path they are
 * served from. The sync script fails if this prefix ever leaves the URDF, so the
 * two cannot silently drift.
 */
const rewriteMeshUrl = (url: string): string => {
  const marker = "nori_description/meshes/";
  const i = url.indexOf(marker);
  return i !== -1 ? `/nori-urdf/meshes/${url.slice(i + marker.length)}` : url;
};

/**
 * Recolour every mesh under the robot and frame the camera on it.
 *
 * Both have to wait for `urdf-processed`: before that the scene graph is empty,
 * so there are no materials to replace and the bounding box is degenerate — which
 * is exactly what made the default view start absurdly zoomed out (the element
 * ships a fov-75 camera parked at z=-10, i.e. ~8x the robot's height away).
 */
function styleAndFrame(
  viewer: URDFViewerElement,
  finishFor: (link: string, material: string) => Finish
) {
  const robot = viewer.robot;
  if (!robot) return;

  // Colour comes from the URDF's own <material> elements — the description is the
  // source of truth, so the model looks the same here, in RViz, and in Isaac.
  // urdf-loader builds those as MeshPhongMaterial, which renders plastic with a
  // hard specular hotspot; swap to Standard and keep the colour so dark parts read
  // as matte moulded plastic rather than polished ceramic.
  robot.traverse((obj: THREE.Object3D) => {
    const mesh = obj as THREE.Mesh;
    if (!mesh.isMesh) return;
    // Walk up to the owning link: materials.yaml binds finishes by LINK name,
    // whereas the URDF binds colour by material name.
    let owner: THREE.Object3D | null = obj;
    while (owner && !/_link$/i.test(owner.name) && owner !== robot) owner = owner.parent;
    const olds = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
    const next = olds.map((m) => {
      const src = m as THREE.MeshPhongMaterial;
      const finish = finishFor(owner?.name ?? "", src?.name ?? "");
      const std = new THREE.MeshStandardMaterial({
        color: src?.color ? src.color.clone() : new THREE.Color(0xdee0e3),
        ...finish,
        transparent: src?.transparent ?? false,
        opacity: src?.opacity ?? 1,
      });
      std.name = src?.name ?? "";
      return std;
    });
    mesh.material = next.length === 1 ? next[0] : next;
    // urdf-loader created the originals and nothing else references them.
    olds.forEach((m) => m?.dispose?.());
  });

  const box = new THREE.Box3().setFromObject(robot);
  if (box.isEmpty()) return;
  const size = new THREE.Vector3();
  const center = new THREE.Vector3();
  box.getSize(size);
  box.getCenter(center);

  // Long lens, matching Robot3D: a narrow fov flattens the perspective so the
  // robot doesn't bow outward at the edges of a small card.
  const camera = viewer.camera;
  camera.fov = 16;
  camera.near = 0.01;
  camera.far = 100;

  // Distance that just contains the robot's largest dimension at this fov, plus
  // headroom so it isn't wedged against the edges.
  const extent = Math.max(size.x, size.y, size.z);
  const dist = (extent / 2 / Math.tan((camera.fov * Math.PI) / 180 / 2)) * 1.45;

  // Slightly off-axis and a touch below centre — the same gentle look-up as the
  // remote page, which reads better than a dead-on elevation.
  camera.position.set(
    center.x + dist * 0.62,
    center.y + size.y * 0.18,
    center.z + dist * 0.78
  );
  camera.updateProjectionMatrix();

  viewer.controls.target.copy(center);
  viewer.controls.update();
  viewer.redraw();
}

/** What the viewer can tell the page about the part under the cursor. */
export type HoveredJoint = {
  name: string;
  type: string;
  lower?: number;
  upper?: number;
};

interface RobotUrdfViewerProps {
  className?: string;
  /** Fires with the joint under the cursor, or null when nothing is hovered. */
  onHoverJoint?: (joint: HoveredJoint | null) => void;
  /** Fires once when the model loads, with every movable joint and its limits. */
  onJointsLoaded?: (joints: HoveredJoint[]) => void;
  /**
   * Fires with every joint's current value whenever the model is posed — on load,
   * and on each drag. With no robot connected this is the only pose information
   * available, so the page can show estimated angles and lift height from the
   * model itself rather than nothing at all.
   */
  onPoseChange?: (pose: Record<string, number>) => void;
}

const RobotUrdfViewer: React.FC<RobotUrdfViewerProps> = ({
  className,
  onHoverJoint,
  onPoseChange,
  onJointsLoaded,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewerRef = useRef<URDFViewerElement | null>(null);
  const { theme } = useContext(ThemeProviderContext);
  const isDark =
    theme === "dark" ||
    (theme === "system" &&
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);

  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");

  // Held in a ref so the mount effect can call the latest callback without
  // listing it as a dependency — depending on it would rebuild the viewer (and
  // refetch ~10 MB of meshes) whenever the parent re-renders.
  const hoverCb = useRef(onHoverJoint);
  hoverCb.current = onHoverJoint;
  const poseCb = useRef(onPoseChange);
  poseCb.current = onPoseChange;
  const jointsCb = useRef(onJointsLoaded);
  jointsCb.current = onJointsLoaded;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const viewer = createUrdfViewer(container, isDark);
    viewerRef.current = viewer;
    setupMeshLoader(viewer, rewriteMeshUrl);

    // createUrdfViewer paints an inline background; clear it so the Tailwind
    // `bg-nori-hf6f4eb` class below wins and the canvas tracks the theme token
    // the rest of the app uses.
    container.style.backgroundColor = "";

    // Joint hover highlight. createUrdfViewer sets LeLab's purple; Nori uses the
    // same green a selected arm turns on the remote page, so hovering here reads
    // as the same interaction.
    viewer.setAttribute("highlight-color", HIGHLIGHT);

    // Match Robot3D's lighting. The element ships its own lights, so replace
    // rather than add — stacking them washes the model out.
    viewer.scene.traverse((o: THREE.Object3D) => {
      const l = o as THREE.Light;
      if (l.isLight) l.intensity = 0;
    });
    // Ambient kept low: it is the enemy of shape. Every extra unit of it lifts the
    // shadowed faces toward the lit ones, so a bright ambient plus a bright key
    // gives a well-exposed model with no form at all.
    const ambient = new THREE.AmbientLight(0xffffff, 0.42);
    // Light positions are in the SCENE's frame, which is three.js-default Y-up —
    // the robot is Z-up only inside the element's `world` container. So "above"
    // here is +Y, not +Z. (The previous key sat at y = -2.4, i.e. underneath the
    // robot, which is why it lit from below.)
    //
    // Raking three-quarter key: high, front, and off to one side. A near-vertical
    // light flattens the model — every upward face gets the same value, so the
    // torso caps and head merge into one silhouette.
    const key = new THREE.DirectionalLight(0xffffff, 1.55);
    key.position.set(5.5, 4.0, 2.0);
    // Cool rim from behind-left to peel the dark plastic off the background.
    const rim = new THREE.DirectionalLight(0xdfe8ff, 0.5);
    rim.position.set(-4.0, 2.0, -3.5);
    // Low fill so shadowed flanks keep some shape instead of going flat black.
    const fill = new THREE.DirectionalLight(0xffffff, 0.14);
    fill.position.set(-2.5, 0.4, 3.5);
    viewer.scene.add(ambient, key, rim, fill);

    // Floor grid, matching the one on the remote page's model.
    //
    // NO rotation, deliberately. `up="Z"` does not make the scene Z-up: the
    // element rotates its inner `world` container instead (see _setUp), so the
    // scene itself stays three.js-default Y-up and GridHelper's native XZ plane
    // is already the ground. Rotating it stands the grid on its edge.
    const grid = new THREE.GridHelper(3, 12, 0xcdc1a8, 0xccc4b6);
    // Invisible to raycasts. urdf-loader's PointerURDFDragControls raycasts the
    // WHOLE scene and takes intersections[0] — the nearest hit — so a floor plane
    // sitting in the scene wins the pick over much of the frame and joints stop
    // highlighting and dragging entirely. A no-op raycast keeps it decorative.
    grid.raycast = () => {};
    viewer.scene.add(grid);

    const onProcessed = () => {
      setStatus("ready");
      // One frame later: geometry is attached during this event, and the
      // bounding box is only correct once it has been.
      window.requestAnimationFrame(async () => {
        let doc: MaterialsDoc | null = null;
        try {
          const res = await fetch("/nori-urdf/materials.json");
          if (res.ok) doc = (await res.json()) as MaterialsDoc;
        } catch {
          /* fall back to DEFAULT_FINISH */
        }
        try {
          styleAndFrame(viewer, buildFinishLookup(doc));
          readPose();
          // Movable joints only: the model has 45 joints but most are fixed frames
          // (cameras, standin shells) with nothing to report.
          const joints = (viewer.robot as unknown as {
            joints?: Record<string, {
              jointType?: string; limit?: { lower?: number; upper?: number };
            }>;
          })?.joints;
          if (joints) {
            jointsCb.current?.(
              Object.entries(joints)
                .filter(([, j]) => j.jointType && j.jointType !== "fixed")
                .map(([name, j]) => ({
                  name,
                  type: j.jointType ?? "unknown",
                  lower: j.limit?.lower,
                  upper: j.limit?.upper,
                }))
            );
          }
        } catch {
          /* element may already be torn down */
        }
      });
    };
    const onError = () => setStatus("error");

    // urdf-loader emits the joint NAME; look the joint itself up on the robot for
    // its type and limits, which is what makes the readout worth showing.
    const onJointOver = (e: Event) => {
      const name = (e as CustomEvent<string>).detail;
      const j = (viewer.robot as unknown as { joints?: Record<string, {
        jointType?: string; limit?: { lower?: number; upper?: number };
      }> })?.joints?.[name];
      hoverCb.current?.({
        name,
        type: j?.jointType ?? "unknown",
        lower: j?.limit?.lower,
        upper: j?.limit?.upper,
      });
    };
    const onJointOut = () => hoverCb.current?.(null);

    const readPose = () => {
      const joints = (viewer.robot as unknown as {
        joints?: Record<string, { angle?: number; jointValue?: number[] }>;
      })?.joints;
      if (!joints) return;
      const pose: Record<string, number> = {};
      for (const [name, j] of Object.entries(joints)) {
        const v = typeof j.angle === "number" ? j.angle : j.jointValue?.[0];
        if (typeof v === "number") pose[name] = v;
      }
      poseCb.current?.(pose);
    };
    const onAngleChange = () => readPose();

    viewer.addEventListener("urdf-processed", onProcessed);
    viewer.addEventListener("error", onError);
    viewer.addEventListener("joint-mouseover", onJointOver);
    viewer.addEventListener("joint-mouseout", onJointOut);
    viewer.addEventListener("angle-change", onAngleChange);

    // `package` must be set even though the mesh loader rewrites full URLs:
    // urdf-loader consults it while resolving package:// before loadMeshFunc runs.
    viewer.setAttribute("package", "/");
    viewer.setAttribute("urdf", URDF_PATH);

    return () => {
      viewer.removeEventListener("urdf-processed", onProcessed);
      viewer.removeEventListener("error", onError);
      viewer.removeEventListener("joint-mouseover", onJointOver);
      viewer.removeEventListener("joint-mouseout", onJointOut);
      viewer.removeEventListener("angle-change", onAngleChange);
      viewerRef.current = null;
      container.innerHTML = "";
    };
    // Theme is handled by the CSS class, so no rebuild on toggle — that would
    // refetch ~10 MB of meshes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={cn("relative", className)}>
      <div
        ref={containerRef}
        className="h-full w-full overflow-hidden rounded-md border bg-nori-hf6f4eb"
      />

      {status === "loading" && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <p className="text-sm text-muted-foreground">Loading robot model…</p>
        </div>
      )}
      {status === "error" && (
        <div className="absolute inset-0 flex items-center justify-center p-4">
          <p className="text-sm text-destructive">Couldn't load the robot model.</p>
        </div>
      )}
    </div>
  );
};

export default RobotUrdfViewer;
