import React, { useContext, useEffect, useRef, useState } from "react";
import * as THREE from "three";

import URDFManipulator from "urdf-loader/src/urdf-manipulator-element.js";
import {
  createUrdfViewer,
  setupMeshLoader,
  URDFViewerElement,
} from "@/lib/urdfViewerHelpers";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import {
  attachPostProcessing,
  BLOOM_LAYER,
  SSAO_SCALE,
  type Post,
} from "@/nori/components/postprocess";
import {
  collectColliders,
  findCollisions,
  type Collider,
  type CollisionPair,
} from "@/nori/components/selfCollision";
import {
  CAMERA_VIEWS,
  PIP,
  startSim,
  type CameraView,
  type SimHandle,
  type SimState,
} from "@/nori/sim/simRuntime";
import {
  liveStateToJointRadians,
  type UrdfJointInfo,
} from "@/nori/components/liveJointPose";
import type { RobotDescriptor } from "@nori/sdk";
import { ThemeProviderContext } from "@/contexts/ThemeContext";
import { cn } from "@/lib/utils";

if (typeof window !== "undefined" && !customElements.get("urdf-viewer")) {
  customElements.define("urdf-viewer", URDFManipulator);
}

/**
 * Renders the real Nori robot description.
 *
 * Deliberately NOT the upstream `UrdfViewer`: that one is bound to LeLab's
 * drag-and-drop context, defaults to the SO-101 arm, and opens a websocket for
 * live joint streaming. None of that applies to showing one fixed, shipped model.
 *
 * Presentation is matched to `nori/remote/Robot3D` (the stylised model on the
 * remote page) so the two read as the same robot: same palette, same lighting,
 * same long-lens low-angle framing. The palette below mirrors the constants in
 * packages/nori-sdk/src/robot-model.ts — if those change, change these.
 *
 * Assets are static files under `public/nori-urdf/`, generated by
 * `nori_ws/urdf_release/tools/sync_to_lelab.py`. Re-run it when the model changes.
 */

const URDF_PATH = "/nori-urdf/nori.urdf";

// Dark-mode scene backgrounds, both aiming at the CARD surface grey
// (--nori-hf3f1e8's dark value) so the viewer reads as one of the cards:
//  - uncomposed: the card colour verbatim, read from the live CSS var;
//  - composed: a pre-grade value hand-solved so ACES @ exposure 0.8 lands on
//    ~the same grey (the raw hex would render near-black after grading).
function darkSceneBg(composed: boolean): string {
  if (composed) return "#313136";
  const v = typeof window !== "undefined"
    ? getComputedStyle(document.documentElement).getPropertyValue("--nori-hf3f1e8").trim()
    : "";
  return v ? `hsl(${v.split(/\s+/).join(",")})` : "#1f1f21";
}

// `?nopost=1` renders straight to the canvas with no composer. Read in two
// places (background choice and composer attach), which must agree.
function hasNoPostFlag() {
  return (
    typeof window !== "undefined" &&
    new URLSearchParams(window.location.search).has("nopost")
  );
}

/**
 * Live lighting overrides from the URL, e.g.
 *   ?exposure=2.4&env=1.6&key=0.8
 *
 * Tuning a lighting chain by editing source, rebuilding and reloading is slow
 * enough that it turns into guesswork — especially when the composited and
 * uncomposited paths differ and you are trying to find the factor between them.
 * These make it one reload per value. They are read once at mount; absent
 * params keep the defaults below.
 */
function lightingOverrides() {
  const q =
    typeof window === "undefined"
      ? new URLSearchParams()
      : new URLSearchParams(window.location.search);
  const num = (k: string, fallback: number) => {
    const v = parseFloat(q.get(k) ?? "");
    return Number.isFinite(v) ? v : fallback;
  };
  return {
    exposure: num("exposure", 0.8),
    env: num("env", 0.2),
    key: num("key", 0.55),
    fill: num("fill", 0.12),
    eye: num("eye", 0.1),
  };
}

const HIGHLIGHT = "#a1d873"; // ARM_ACTIVE — the green a selected arm turns on the remote page

/**
 * Surface finish, from the description's own `materials.yaml` — the team's
 * render-validated PBR values (roughness / metallic per link), shipped alongside
 * the model as `materials.json` by sync_to_lelab.py.
 *
 * URDF carries colour and nothing else, so without this the viewer has to invent
 * surface properties. Colour still comes from the URDF <material> elements: those
 * include the stylised standin palette (white head, caps) that materials.yaml has
 * no opinion on, since it only describes the two real robot finishes.
 */
type Finish = { roughness: number; metalness: number };
const DEFAULT_FINISH: Finish = { roughness: 0.78, metalness: 0.06 };

type MaterialsDoc = {
  materials?: Record<string, { roughness?: number; metallic?: number }>;
  assign?: Record<string, string>;
};

/**
 * Per-link overrides applied ON TOP of materials.yaml.
 *
 * TEMPORARY. materials.yaml still describes the lift as foam-covered
 * (body_mat, roughness 0.9, metallic 0.0), which is stale — the lift is bare
 * metal now. The fix belongs in materials.yaml itself, since that file also feeds
 * the SDG renderer; this only stops the viewer showing something we know is wrong
 * in the meantime. DELETE THIS once materials.yaml is corrected.
 */
/**
 * Finishes keyed by URDF MATERIAL name, checked before anything link-based.
 *
 * materials.yaml binds finishes per link, which cannot express a link carrying
 * several surfaces — head_link alone is white shell, glass screen and lit eyes.
 * Material name is the finer-grained key, so it wins.
 */
const MATERIAL_FINISHES: Record<string, Finish> = {
  nori_screen: { roughness: 0.08, metalness: 0.85 }, // glossy display glass
  nori_eye: { roughness: 0.25, metalness: 0.1 },
};

const FINISH_OVERRIDES: Record<string, Finish> = {
  lift_bottom_link: { roughness: 0.24, metalness: 0.92 },
  lift_middle_link: { roughness: 0.24, metalness: 0.92 },
  lift_top_link: { roughness: 0.24, metalness: 0.92 },
};

function buildFinishLookup(
  doc: MaterialsDoc | null
): (link: string, material: string) => Finish {
  if (!doc?.materials || !doc?.assign)
    return (link: string, material: string) =>
      MATERIAL_FINISHES[material] ?? FINISH_OVERRIDES[link] ?? DEFAULT_FINISH;
  const finishFor = (matName: string | undefined): Finish => {
    const m = matName ? doc.materials?.[matName] : undefined;
    return m
      ? { roughness: m.roughness ?? DEFAULT_FINISH.roughness, metalness: m.metallic ?? 0 }
      : DEFAULT_FINISH;
  };
  const fallback = finishFor(doc.assign.default);
  return (link: string, material: string) =>
    MATERIAL_FINISHES[material] ??
    FINISH_OVERRIDES[link] ??
    (doc.assign?.[link] ? finishFor(doc.assign[link]) : fallback);
}

/**
 * The URDF addresses meshes as `package://nori_description/meshes/...`, a ROS
 * convention the browser knows nothing about. Rewrite to the static path they are
 * served from. The sync script fails if this prefix ever leaves the URDF, so the
 * two cannot silently drift.
 */
const rewriteMeshUrl = (url: string): string => {
  const marker = "nori_description/meshes/";
  const i = url.indexOf(marker);
  return i !== -1 ? `/nori-urdf/meshes/${url.slice(i + marker.length)}` : url;
};

/**
 * Recolour every mesh under the robot and frame the camera on it.
 *
 * Both have to wait for `urdf-processed`: before that the scene graph is empty,
 * so there are no materials to replace and the bounding box is degenerate — which
 * is exactly what made the default view start absurdly zoomed out (the element
 * ships a fov-75 camera parked at z=-10, i.e. ~8x the robot's height away).
 */
function styleAndFrame(
  viewer: URDFViewerElement,
  finishFor: (link: string, material: string) => Finish
) {
  const eyeIntensity = lightingOverrides().eye;
  const robot = viewer.robot;
  if (!robot) return;

  // Colour comes from the URDF's own <material> elements — the description is the
  // source of truth, so the model looks the same here, in RViz, and in Isaac.
  // urdf-loader builds those as MeshPhongMaterial, which renders plastic with a
  // hard specular hotspot; swap to Standard and keep the colour so dark parts read
  // as matte moulded plastic rather than polished ceramic.
  robot.traverse((obj: THREE.Object3D) => {
    const mesh = obj as THREE.Mesh;
    if (!mesh.isMesh) return;
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    // Walk up to the owning link: materials.yaml binds finishes by LINK name,
    // whereas the URDF binds colour by material name.
    let owner: THREE.Object3D | null = obj;
    while (owner && !/_link$/i.test(owner.name) && owner !== robot) owner = owner.parent;
    const olds = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
    const next = olds.map((m) => {
      const src = m as THREE.MeshPhongMaterial;
      const finish = finishFor(owner?.name ?? "", src?.name ?? "");
      const std = new THREE.MeshStandardMaterial({
        color: src?.color ? src.color.clone() : new THREE.Color(0xdee0e3),
        ...finish,
        transparent: src?.transparent ?? false,
        opacity: src?.opacity ?? 1,
        // Double-sided on purpose. The visual meshes are decimated OPEN shells
        // exported from CAD, and some exports carry whole patches wound inward
        // (elbow_pitch and forearm_yaw are measurably winding-inconsistent).
        // With default front-side culling an inward patch renders as a hole in
        // the part — invisible in mesh editors, which preview double-sided.
        // Backface cost on a ~150k-tri scene is negligible.
        side: THREE.DoubleSide,
      });
      // The eyes are the one thing on this robot that should look lit rather
      // than lit-upon. Emissive drives them past the bloom threshold (0.92) so
      // they glow, while nothing else on the model — not even the white shell —
      // gets near it.
      if (src?.name === "nori_eye") {
        std.emissive = new THREE.Color(0xdfefff);
        std.emissiveIntensity = eyeIntensity;
        std.toneMapped = true;
        // Opt this mesh into the bloom pass. Nothing else on the robot is on
        // this layer, so nothing else can glow however bright it renders.
        mesh.layers.enable(BLOOM_LAYER);
      }
      std.name = src?.name ?? "";
      return std;
    });
    mesh.material = next.length === 1 ? next[0] : next;
    // urdf-loader created the originals and nothing else references them.
    olds.forEach((m) => m?.dispose?.());
  });

  const box = new THREE.Box3().setFromObject(robot);
  if (box.isEmpty()) return;
  const size = new THREE.Vector3();
  const center = new THREE.Vector3();
  box.getSize(size);
  box.getCenter(center);

  // Long lens, matching Robot3D: a narrow fov flattens the perspective so the
  // robot doesn't bow outward at the edges of a small card.
  const camera = viewer.camera;
  camera.fov = 16;
  // Tight near/far, because SSAO reads the depth buffer.
  //
  // The default 0.01/100 is a 10,000:1 ratio, and depth precision is distributed
  // logarithmically — almost all of it lands in the first few centimetres, so at
  // robot distance neighbouring surfaces become indistinguishable. SSAO then
  // reads that noise as occlusion and darkens everything uniformly, which is
  // what made the composited image far darker than the raw one.
  //
  // A 1.3 m robot viewed from a few metres needs nothing like that range; 200:1
  // gives the depth buffer somewhere useful to spend its bits.
  camera.near = 0.05;
  camera.far = 20;

  // Distance that just contains the robot's largest dimension at this fov, plus
  // a little headroom so it isn't wedged against the edges. (1.45 read as
  // zoomed-out — the robot floated small in the frame; 2026-08-25.)
  const extent = Math.max(size.x, size.y, size.z);
  const dist = (extent / 2 / Math.tan((camera.fov * Math.PI) / 180 / 2)) * 1.0;

  // Slightly off-axis and a touch below centre — the same gentle look-up as the
  // remote page, which reads better than a dead-on elevation.
  camera.position.set(
    center.x + dist * 0.62,
    center.y + size.y * 0.18,
    center.z + dist * 0.78
  );
  camera.updateProjectionMatrix();

  viewer.controls.target.copy(center);
  viewer.controls.update();
  viewer.redraw();
}

/**
 * Programmatic handle to the viewer, for choreographed sequences (the ?demo=1
 * release animation). Everything here goes through the same paths as user
 * interaction — setJoint fires the element's own angle-change event, so the
 * pose readout, mimic joints and collision check all react exactly as if a
 * person dragged the joint.
 */
export type ViewerApi = {
  setJoint: (name: string, value: number) => void;
  /** Green-highlight the link a joint drives, as hover does. Null clears. */
  highlightJoint: (name: string | null) => void;
  /** Place the camera on a sphere around the robot's centre. Radians, metres.
   *  targetYOffset raises the LOOK point without moving the orbit centre — the
   *  lift raises the robot ~0.5 m and a fixed target crops the head off. */
  orbit: (azimuth: number, elevation: number, distance: number, targetYOffset?: number) => void;
  frame: () => void;
  /** The robot's root Object3D (URDF/base coordinates). For choreography
   *  props (e.g. the ?traj=1 whiteboard) that must ride the robot's frame —
   *  attach children here and their coordinates are plain base-frame metres. */
  getRobotRoot: () => THREE.Object3D | null;
  /** Request a render after out-of-band scene changes (e.g. texture paint). */
  redraw: () => void;
};

/** What the viewer can tell the page about the part under the cursor. */
export type HoveredJoint = {
  name: string;
  type: string;
  lower?: number;
  upper?: number;
};

interface RobotUrdfViewerProps {
  className?: string;
  /** Fires with the joint under the cursor, or null when nothing is hovered. */
  onHoverJoint?: (joint: HoveredJoint | null) => void;
  /**
   * Fires whenever the pose changes with the links currently intersecting each
   * other. Kinematic only — geometry and joint limits, no physics.
   */
  onCollisions?: (pairs: CollisionPair[]) => void;
  /**
   * Run the self-collision check. Off by default: it is a diagnostic, not
   * something someone browsing the model asked for, and a red panel on a page
   * whose job is "here is our robot" reads as a fault rather than a feature.
   */
  collisionCheck?: boolean;
  /** Hands the page a programmatic handle once the model is ready. */
  onViewerReady?: (api: ViewerApi) => void;
  /** Fires once when the model loads, with every movable joint and its limits. */
  onJointsLoaded?: (joints: HoveredJoint[]) => void;
  /**
   * Fires with every joint's current value whenever the model is posed — on load,
   * and on each drag. With no robot connected this is the only pose information
   * available, so the page can show estimated angles and lift height from the
   * model itself rather than nothing at all.
   */
  onPoseChange?: (pose: Record<string, number>) => void;
  /**
   * Drive the robot around a parametric apartment with the keyboard.
   *
   * Kinematic, not physical — see nori/sim/driveModel. Toggling this in and out
   * is fully reversible and does NOT reload the model, which is the reason the
   * sim is a function applied to this viewer rather than a second viewer.
   */
  sim?: boolean;
  /** Which of the robot's own cameras to inset while driving. Null hides it. */
  simCameraView?: CameraView | null;
  /** Live driving state while `sim` is on, at about 10 Hz, and only on change. */
  onSimState?: (state: SimState) => void;
  /** Fires when the inset itself is clicked to step to the next camera. */
  onSimCameraViewChange?: (view: CameraView) => void;
  /**
   * Whether this is a viewer or a picture.
   *
   * `false` gives a display-only render: no joint hover, no joint dragging, no
   * post-processing chain, and no redraw unless the view actually changes. That
   * is what a small schematic panel wants — and on the remote page it shares a
   * GPU with a live video call, where sixty composited frames a second of a
   * model nobody is touching is pure waste. The camera can still be orbited,
   * which the panel it replaces there could do too.
   */
  interactive?: boolean;
  // Drop the container's own rounded border — for hosts (the remote page's
  // stage/PIP) that draw their own frame around the viewer; a second inner
  // border reads as a misaligned double edge at the corners.
  frameless?: boolean;
  /**
   * Live joint telemetry (the teleop `state` dict, ~15 Hz). When present, the
   * model is posed from it on every frame; when absent the viewer stays a
   * static (draggable) model exactly as before. See liveJointPose.ts for the
   * key → joint mapping and denormalization.
   */
  liveState?: Record<string, number>;
  /** The robot's handshake descriptor, for future radian ranges (ranges_rad). */
  descriptor?: RobotDescriptor;
}

/** One-finger behaviour on touch screens. */
type TouchMode = "pose" | "camera";

const RobotUrdfViewer: React.FC<RobotUrdfViewerProps> = ({
  className,
  onHoverJoint,
  onPoseChange,
  onJointsLoaded,
  onCollisions,
  onViewerReady,
  collisionCheck = false,
  sim = false,
  simCameraView = "front",
  onSimState,
  onSimCameraViewChange,
  interactive = true,
  frameless = false,
  liveState,
  descriptor,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewerRef = useRef<URDFViewerElement | null>(null);
  const { theme } = useContext(ThemeProviderContext);
  const isDark =
    theme === "dark" ||
    (theme === "system" &&
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);

  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  // "ready" means the geometry is in the scene; `prepared` means the one-frame
  // -later pass that restyles the materials and frames the camera has ALSO run.
  // The sim needs the second, not the first: it saves the camera to restore on
  // exit and sets up its own framing, and starting it a frame early meant
  // styleAndFrame overwrote both immediately afterwards.
  const [prepared, setPrepared] = useState(false);

  // On touch screens one-finger drag can only mean ONE thing at a time: with
  // OrbitControls' default it orbits the camera, which makes posing joints
  // impossible (there is no hover to disambiguate, unlike a mouse). So touch
  // devices get an explicit mode: "pose" frees the single finger for joint
  // dragging, "camera" gives it back to orbit. Two-finger pinch/pan keeps
  // working in BOTH modes — only the one-finger binding changes.
  const isCoarse =
    typeof window !== "undefined" &&
    window.matchMedia("(pointer: coarse)").matches;
  const [touchMode, setTouchMode] = useState<TouchMode>("pose");
  const touchModeRef = useRef(touchMode);
  touchModeRef.current = touchMode;

  // Live telemetry → model pose. Mutates the loaded robot in place (mirrors
  // Robot3D's pattern): no scene rebuild at the 15 Hz telemetry rate. Gated on
  // `prepared` so a frame that arrives before the model loads is dropped — and
  // because the effect ALSO re-runs when `prepared` flips true, the latest
  // frame is applied the moment a late-loading model is ready.
  useEffect(() => {
    const viewer = viewerRef.current;
    if (!prepared || !liveState || !viewer?.robot) return;
    const joints = (viewer.robot as unknown as { joints?: Record<string, UrdfJointInfo> })
      .joints;
    if (!joints) return;
    const pose = liveStateToJointRadians(liveState, joints, descriptor);
    // Batch through the element's setJointValues (present at runtime, not in
    // our helper's interface type) so mimics and angle-change events fire as
    // usual. Each changed joint marks the element dirty; the element's render
    // loop draws dirty frames even with auto-redraw removed (the interactive
    // path), so one redraw per telemetry frame — and none when nothing moved.
    const batch = (viewer as unknown as {
      setJointValues?: (values: Record<string, number>) => void;
    }).setJointValues;
    if (typeof batch === "function") {
      batch.call(viewer, pose);
    } else {
      for (const [name, rad] of Object.entries(pose)) viewer.setJointValue(name, rad);
      viewer.redraw();
    }
  }, [liveState, descriptor, prepared]);

  // Held in a ref so the mount effect can call the latest callback without
  // listing it as a dependency — depending on it would rebuild the viewer (and
  // refetch ~10 MB of meshes) whenever the parent re-renders.
  const hoverCb = useRef(onHoverJoint);
  hoverCb.current = onHoverJoint;
  const poseCb = useRef(onPoseChange);
  poseCb.current = onPoseChange;
  const jointsCb = useRef(onJointsLoaded);
  jointsCb.current = onJointsLoaded;
  const collisionCb = useRef(onCollisions);
  collisionCb.current = onCollisions;
  const checkOn = useRef(collisionCheck);
  checkOn.current = collisionCheck;
  const collidersRef = useRef<Collider[]>([]);
  const postRef = useRef<Post | null>(null);
  const readyCb = useRef(onViewerReady);
  readyCb.current = onViewerReady;
  // Handed to the sim so its shadow can travel with the robot and its floor can
  // replace the grid. Captured at mount rather than looked up by traversal.
  const keyLightRef = useRef<THREE.DirectionalLight | null>(null);
  const gridRef = useRef<THREE.Object3D | null>(null);
  const simRef = useRef<SimHandle | null>(null);
  const simStateCb = useRef(onSimState);
  simStateCb.current = onSimState;
  // Read once when the sim starts. Held in a ref so changing the inset camera
  // does not restart the sim (which would put the robot back at the door).
  const simViewRef = useRef(simCameraView);
  simViewRef.current = simCameraView;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const viewer = createUrdfViewer(container, isDark);
    viewerRef.current = viewer;
    setupMeshLoader(viewer, rewriteMeshUrl);

    if (!interactive) {
      // The element wires pointer handlers for joint picking the moment it is
      // connected. dispose() only unbinds them, and is safe to call again when
      // the element tears itself down.
      (viewer as unknown as { dragControls?: { dispose: () => void } })
        .dragControls?.dispose();
      // A non-interactive viewer is a display, not a control: freeze the camera
      // too, or pointer drags still orbit it (and drag-selection highlights the
      // surrounding page while they do).
      (viewer.controls as unknown as { enabled?: boolean }).enabled = false;
      // Draw when something changes, and not otherwise. See `interactive`.
      viewer.removeAttribute("auto-redraw");
      (viewer.controls as unknown as {
        addEventListener?: (t: string, f: () => void) => void;
      }).addEventListener?.("change", () => viewer.redraw());
    }

    // createUrdfViewer paints an inline background; clear it so the Tailwind
    // `bg-nori-hf6f4eb` class below wins and the canvas tracks the theme token
    // the rest of the app uses.
    container.style.backgroundColor = "";

    // Joint hover highlight. createUrdfViewer sets LeLab's purple; Nori uses the
    // same green a selected arm turns on the remote page, so hovering here reads
    // as the same interaction.
    viewer.setAttribute("highlight-color", HIGHLIGHT);
    // The element's hover highlight SWAPS mesh materials for its own — which is
    // front-side by default. Every base material here is DoubleSide (the meshes
    // are open shells), so a single-sided highlight reintroduces the culling
    // holes exactly while a link is highlighted. Same for the demo highlight.
    const hl = (viewer as unknown as { highlightMaterial?: THREE.Material }).highlightMaterial;
    if (hl) hl.side = THREE.DoubleSide;

    // LIGHTING — deliberately rebuilt from nothing.
    //
    // Three parties add lights to this scene before we get here: the
    // urdf-viewer element (a HemisphereLight, and a DirectionalLight at
    // intensity Math.PI), and createUrdfViewer (an AmbientLight at 1.0 and a
    // DirectionalLight at 0.8). Stacked with an environment map that is itself
    // a full lighting solution, the model washes out — and muting them by
    // setting intensity to 0 leaves them in the graph to be re-enabled by
    // anything that walks it.
    //
    // So they are REMOVED, and exactly what is wanted is added back. If the
    // scene ever looks doubly-lit again, count the lights: there should be two.
    const preexisting: THREE.Object3D[] = [];
    viewer.scene.traverse((o: THREE.Object3D) => {
      if ((o as THREE.Light).isLight) preexisting.push(o);
    });
    preexisting.forEach((l) => l.removeFromParent());

    // The environment map carries the lighting; these two are supporting.
    //
    // The key is kept mainly for the SHADOW — a directional light is what casts
    // one, and an environment map alone leaves the robot floating with nothing
    // anchoring it to the floor. It is deliberately weak enough that the shading
    // is mostly image-based, so surfaces pick up tinted reflections rather than
    // flat white.
    //
    // Intensities are in three's physical units (r155+), where legacy 1.0 is
    // about Math.PI.
    const L = lightingOverrides();
    // Warm-white key/fill (~4500K). With the environment dialled low the
    // direct lights carry the shading, so their colour is what tints the model.
    const key = new THREE.DirectionalLight(0xffe9d2, L.key);
    key.position.set(4.0, 5.5, 3.0);
    // The element's own directional light was the shadow caster; removing it
    // above killed shadows entirely. A grounded contact shadow is the single
    // biggest thing separating "a render" from "a model floating in a void",
    // so the replacement key takes the job over. Tight ortho bounds keep the
    // shadow map's texels dense enough to stay crisp on a ~1.3 m robot.
    key.castShadow = true;
    key.shadow.mapSize.set(2048, 2048);
    const sc = key.shadow.camera as THREE.OrthographicCamera;
    sc.left = -1.6; sc.right = 1.6; sc.top = 1.6; sc.bottom = -1.6;
    sc.near = 0.1; sc.far = 14;
    key.shadow.bias = -0.0004;
    key.shadow.normalBias = 0.02;
    const fill = new THREE.DirectionalLight(0xfff1e0, L.fill);
    fill.position.set(-3.0, 1.5, 3.5);
    viewer.scene.add(key, fill);
    keyLightRef.current = key;

    // Floor grid, matching the one on the remote page's model.
    //
    // NO rotation, deliberately. `up="Z"` does not make the scene Z-up: the
    // element rotates its inner `world` container instead (see _setUp), so the
    // scene itself stays three.js-default Y-up and GridHelper's native XZ plane
    // is already the ground. Rotating it stands the grid on its edge.
    // Image-based lighting. A single environment map does more for how machined
    // metal and moulded plastic read than any number of directional lights: it
    // gives every surface something to reflect. RoomEnvironment ships with
    // three, so this costs no download.
    const renderer = (viewer as unknown as { renderer?: THREE.WebGLRenderer }).renderer;
    if (renderer) {
      renderer.toneMapping = THREE.ACESFilmicToneMapping;
      // Exposure is the safe brightness dial. The pass order is
      //   scene -> TAA -> SSAO -> bloom -> OutputPass
      // and OutputPass is where tone mapping happens, so exposure is applied
      // AFTER bloom has already decided what glows. Raising it brightens the
      // image without pushing more pixels over the bloom threshold.
      //
      // environmentIntensity and the key light are the opposite: they run
      // before bloom, so raising those to brighten things brings the veiling
      // back. Reach for exposure first.
      renderer.toneMappingExposure = L.exposure;
      // Studio HDRI, downsampled to 512x256 from the 2k original. The map is
      // never drawn — it only lights — and PMREM convolves it heavily for the
      // diffuse and rough mips, so resolution beyond this buys nothing visible
      // while costing 6.1 MB instead of 512 KB. Downsampled in linear light, so
      // mean radiance is preserved to 0.36% (the RGBE mantissa, not the resize).
      const pmrem = new THREE.PMREMGenerator(renderer);
      pmrem.compileEquirectangularShader();

      // A procedural environment goes in immediately, then the HDRI replaces it
      // when it arrives. Two reasons: the model is never unlit (the direct
      // lights here are deliberately weak because IBL is meant to carry the
      // scene, so a missing environment reads as "everything is too dark"), and
      // a failed fetch degrades instead of silently removing the lighting —
      // which is indistinguishable from a tuning problem and wastes an
      // afternoon.
      viewer.scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
      viewer.redraw();

      new RGBELoader().load(
        "/env/studio_loft_512.hdr",
        (hdrTexture) => {
          hdrTexture.mapping = THREE.EquirectangularReflectionMapping;
          const prev = viewer.scene.environment;
          const baked = pmrem.fromEquirectangular(hdrTexture).texture;
          viewer.scene.environment = baked;
          // `?showenv=1` draws the environment as the background — the direct
          // answer to "is my HDRI even loading?". If you see the studio loft,
          // it is; if you see the flat page colour, it is not.
          if (new URLSearchParams(window.location.search).has("showenv")) {
            viewer.scene.background = baked;
          }
          prev?.dispose();
          hdrTexture.dispose();
          viewer.redraw();
          // Recorder gate: the demo capture must not start until the FINAL
          // environment is lit, or the video shows the fallback-to-HDRI tint
          // swap mid-take. Also set on error below so a failed fetch degrades
          // instead of deadlocking the recorder.
          (window as unknown as { __noriEnvReady?: boolean }).__noriEnvReady = true;
        },
        undefined,
        (err) => {
          // Loud on purpose: the fallback means the page still looks fine, so
          // nothing else would tell you the HDRI never loaded.
          console.error("[RobotUrdfViewer] environment map failed to load", err);
          (window as unknown as { __noriEnvReady?: boolean }).__noriEnvReady = true;
        }
      );
      // Reflections and fill, dialled well back — enough to give metal something
      // to reflect without lifting everything toward grey.
      // This is the colour dial, not just a brightness one. Direct lights are
      // white, so they only ever add white; the environment is what puts tinted
      // reflections on the metal and the gloss. Dropping it to compensate for
      // the earlier over-brightness is what made the model look grey — the fix
      // for "too bright" was removing the six redundant LIGHTS, not muting this.
      viewer.scene.environmentIntensity = L.env;
      // Whether this instance will render through the EffectComposer (see the
      // post-processing block below) decides which background colour is right.
      const willCompose = Boolean(renderer) && !hasNoPostFlag() && interactive;
      // `environment` lights the scene; `background` is what you SEE.
      //
      // The background is painted EXPLICITLY rather than left transparent for
      // the container colour to show through. Once rendering is routed through
      // an EffectComposer the canvas is no longer composited over the page —
      // the passes write to opaque offscreen targets — so a null background
      // came out black. Reading the same theme token the container uses keeps
      // the two identical and flat.
      //
      // Still do NOT put the environment map here: it would fill the frame with
      // a photographic room.
      // The background rides through the same ACES tone mapping and exposure as
      // the robot, and ACES compresses AND desaturates midtones — at exposure
      // 0.8 a warm paper white comes out cool grey. So this is NOT the colour
      // that appears on screen: it is the pre-grade source, hand-tuned so the
      // graded result reads as warm paper next to the page's own hfffdf7
      // backdrop. The 1.35 factor is exposure headroom (fine in a HalfFloat
      // chain); ffedcf is the tuned hex. Change it via `?bg=<hex>`, judge by
      // eye, then bake the winner here.
      //
      // ONLY valid with the composer attached, though. Without it (a
      // non-interactive viewer, or `?nopost=1`) a Color background never
      // passes through tone mapping at all — three routes it to the GL clear
      // color — so the pre-grade source would hit the screen raw: ×1.35
      // clips to a maxed-out yellow. In that path, paint the POST-grade
      // colour directly instead.
      if (willCompose) {
        const bg = new THREE.Color(isDark ? darkSceneBg(true) : "#ffedcf");
        const bgHex = new URLSearchParams(window.location.search).get("bg");
        if (bgHex && /^[0-9a-fA-F]{6}$/.test(bgHex)) bg.set(`#${bgHex}`);
        if (!isDark || bgHex) bg.multiplyScalar(1.35);
        viewer.scene.background = bg;
      } else {
        // Light: near what the graded ffedcf lands at through ACES @ 0.8,
        // desaturated a touch. Dark: the card grey verbatim.
        viewer.scene.background = new THREE.Color(
          isDark ? darkSceneBg(false) : "#e9e5db"
        );
      }
    }

    // Post-processing. Attached after the lights and environment so the passes
    // see the finished scene. TAA also replaces the MSAA that goes away the
    // moment rendering is routed through an offscreen target.
    // `?nopost=1` renders straight to the canvas with no composer. This exists
    // because "it looks too dark" has two completely different causes — the
    // lighting rig, or the passes subtracting from it — and they are impossible
    // to tell apart by eye when both are on. Compare the two and you know which
    // half to tune.
    if (renderer && !hasNoPostFlag() && interactive) {
      const rect = container.getBoundingClientRect();
      postRef.current = attachPostProcessing(
        renderer,
        viewer.scene,
        viewer.camera,
        { width: Math.max(1, rect.width), height: Math.max(1, rect.height) }
      );
      // Any camera move or pose change makes accumulated samples stale.
      viewer.controls.addEventListener?.("change", () => postRef.current?.invalidate());
      viewer.addEventListener("angle-change", () => postRef.current?.invalidate());
    }

    const grid = new THREE.GridHelper(3, 12, 0xcdc1a8, 0xccc4b6);
    // Invisible to raycasts. urdf-loader's PointerURDFDragControls raycasts the
    // WHOLE scene and takes intersections[0] — the nearest hit — so a floor plane
    // sitting in the scene wins the pick over much of the frame and joints stop
    // highlighting and dragging entirely. A no-op raycast keeps it decorative.
    grid.raycast = () => {};
    viewer.scene.add(grid);
    gridRef.current = grid;

    const onProcessed = () => {
      setStatus("ready");
      // One frame later: geometry is attached during this event, and the
      // bounding box is only correct once it has been.
      window.requestAnimationFrame(async () => {
        let doc: MaterialsDoc | null = null;
        try {
          const res = await fetch("/nori-urdf/materials.json");
          if (res.ok) doc = (await res.json()) as MaterialsDoc;
        } catch {
          /* fall back to DEFAULT_FINISH */
        }
        try {
          styleAndFrame(viewer, buildFinishLookup(doc));
          // styleAndFrame is what finally sets the camera's near and far, and
          // ambient occlusion is scaled against that range — so its metres have
          // to be converted again now, not at the moment the pass was built.
          postRef.current?.setSsaoScale(SSAO_SCALE.radius, SSAO_SCALE.range);
          readPose();
          // Hide collision geometry and index it for the self-collision test.
          robotColliders(viewer);
          // Movable joints only: the model has 45 joints but most are fixed frames
          // (cameras, standin shells) with nothing to report.
          const joints = (viewer.robot as unknown as {
            joints?: Record<string, {
              jointType?: string; limit?: { lower?: number; upper?: number };
            }>;
          })?.joints;
          if (joints) {
            handOutApi(viewer);
            jointsCb.current?.(
              Object.entries(joints)
                .filter(([, j]) => j.jointType && j.jointType !== "fixed")
                .map(([name, j]) => ({
                  name,
                  type: j.jointType ?? "unknown",
                  lower: j.limit?.lower,
                  upper: j.limit?.upper,
                }))
            );
          }
        } catch {
          /* element may already be torn down */
        }
        setPrepared(true);
      });
    };
    const onError = () => setStatus("error");

    // urdf-loader emits the joint NAME; look the joint itself up on the robot for
    // its type and limits, which is what makes the readout worth showing.
    const onJointOver = (e: Event) => {
      const name = (e as CustomEvent<string>).detail;
      const j = (viewer.robot as unknown as { joints?: Record<string, {
        jointType?: string; limit?: { lower?: number; upper?: number };
      }> })?.joints?.[name];
      hoverCb.current?.({
        name,
        type: j?.jointType ?? "unknown",
        lower: j?.limit?.lower,
        upper: j?.limit?.upper,
      });
    };
    const onJointOut = () => hoverCb.current?.(null);

    const readPose = () => {
      const joints = (viewer.robot as unknown as {
        joints?: Record<string, { angle?: number; jointValue?: number[] }>;
      })?.joints;
      if (!joints) return;
      const pose: Record<string, number> = {};
      for (const [name, j] of Object.entries(joints)) {
        const v = typeof j.angle === "number" ? j.angle : j.jointValue?.[0];
        if (typeof v === "number") pose[name] = v;
      }
      poseCb.current?.(pose);
    };
    const onAngleChange = () => {
      readPose();
      runCollisionCheck(viewer);
    };

    const robotColliders = (v: URDFViewerElement) => {
      if (!v.robot) return;
      v.robot.traverse((o: THREE.Object3D) => {
        if ((o as unknown as { isURDFCollider?: boolean }).isURDFCollider) {
          o.visible = false;
        }
      });
      collidersRef.current = collectColliders(v.robot);
      runCollisionCheck(v);
    };

    // Same visual the manipulator uses on hover, driven programmatically. The
    // traversal rule matches the element's: colour every mesh under the joint,
    // stopping where a deeper movable joint begins.
    const demoHighlight = new THREE.MeshStandardMaterial({
      color: 0xa1d873,
      emissive: 0xa1d873,
      emissiveIntensity: 0.25,
      roughness: 0.6,
      side: THREE.DoubleSide, // matches the base materials — see note above
    });
    const highlighted = new Map<THREE.Mesh, THREE.Material | THREE.Material[]>();
    const clearHighlight = () => {
      highlighted.forEach((m, mesh) => (mesh.material = m));
      highlighted.clear();
    };
    const applyHighlight = (root: THREE.Object3D) => {
      const walk = (o: THREE.Object3D, isRoot: boolean) => {
        const j = o as unknown as { isURDFJoint?: boolean; jointType?: string };
        if (!isRoot && j.isURDFJoint && j.jointType !== "fixed") return;
        const mesh = o as THREE.Mesh;
        if (mesh.isMesh && !(o as unknown as { isURDFCollider?: boolean }).isURDFCollider) {
          if (!highlighted.has(mesh)) {
            highlighted.set(mesh, mesh.material);
            mesh.material = demoHighlight;
          }
        }
        o.children.forEach((c) => walk(c, false));
      };
      walk(root, true);
    };

    const handOutApi = (v: URDFViewerElement) => {
      const robot = v.robot as unknown as {
        joints?: Record<string, THREE.Object3D>;
      };
      readyCb.current?.({
        setJoint: (name, value) => v.setJointValue(name, value),
        getRobotRoot: () => (v.robot as unknown as THREE.Object3D) ?? null,
        redraw: () => {
          v.redraw();
          postRef.current?.invalidate();
        },
        highlightJoint: (name) => {
          clearHighlight();
          if (name && robot?.joints?.[name]) applyHighlight(robot.joints[name]);
          v.redraw();
          postRef.current?.invalidate();
        },
        orbit: (azimuth, elevation, distance, targetYOffset = 0) => {
          const t = v.controls.target.clone();
          t.y += targetYOffset;
          v.camera.position.set(
            t.x + distance * Math.cos(elevation) * Math.cos(azimuth),
            t.y + distance * Math.sin(elevation),
            t.z + distance * Math.cos(elevation) * Math.sin(azimuth)
          );
          v.camera.lookAt(t);
          v.controls.update();
          v.redraw();
          postRef.current?.invalidate();
        },
        frame: () => {
          v.redraw();
          postRef.current?.invalidate();
        },
      });
    };

    const runCollisionCheck = (v: URDFViewerElement) => {
      if (!v.robot || !collisionCb.current) return;
      if (!checkOn.current || collidersRef.current.length === 0) {
        collisionCb.current([]);
        return;
      }
      collisionCb.current(findCollisions(v.robot, collidersRef.current));
    };

    viewer.addEventListener("urdf-processed", onProcessed);
    viewer.addEventListener("error", onError);
    viewer.addEventListener("joint-mouseover", onJointOver);
    viewer.addEventListener("joint-mouseout", onJointOut);
    viewer.addEventListener("angle-change", onAngleChange);

    // `package` must be set even though the mesh loader rewrites full URLs:
    // urdf-loader consults it while resolving package:// before loadMeshFunc runs.
    // The viewer element always parses collision geometry (urdf-viewer-element
    // sets loader.parseCollision unconditionally) and hides it unless
    // `show-collision` is set — so the shapes are already in the scene, already
    // invisible, and just need indexing for the self-collision test.
    // Turns on the element's shadow-receiving ground plane, which it keeps
    // parked just under the robot's bounding box.
    viewer.setAttribute("display-shadow", "");
    viewer.setAttribute("package", "/");
    viewer.setAttribute("urdf", URDF_PATH);

    const onResize = () => {
      const r = container.getBoundingClientRect();
      postRef.current?.setSize(Math.max(1, r.width), Math.max(1, r.height));
      postRef.current?.invalidate();
    };
    const ro = new ResizeObserver(onResize);
    ro.observe(container);

    return () => {
      ro.disconnect();
      postRef.current?.dispose();
      postRef.current = null;
      viewer.removeEventListener("urdf-processed", onProcessed);
      viewer.removeEventListener("error", onError);
      viewer.removeEventListener("joint-mouseover", onJointOver);
      viewer.removeEventListener("joint-mouseout", onJointOut);
      viewer.removeEventListener("angle-change", onAngleChange);
      viewerRef.current = null;
      container.innerHTML = "";
    };
    // Theme is handled by the CSS class, so no rebuild on toggle — that would
    // refetch ~10 MB of meshes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // The scene background, though, is BAKED into the viewer at mount — the
  // effect above runs once, so a theme toggle left the canvas painting the
  // old theme's colour over the (correctly flipped) container token. Repaint
  // just the background on theme change; lights/materials read fine in both.
  useEffect(() => {
    const v = viewerRef.current;
    if (!v?.scene) return;
    const composed = Boolean(postRef.current);
    let bg: THREE.Color;
    if (composed) {
      // Pre-grade source — same recipe as mount (see the comment there).
      bg = new THREE.Color(isDark ? darkSceneBg(true) : "#ffedcf");
      if (!isDark) bg.multiplyScalar(1.35);
    } else {
      bg = new THREE.Color(isDark ? darkSceneBg(false) : "#e9e5db");
    }
    v.scene.background = bg;
    v.redraw();
    postRef.current?.invalidate();
  }, [isDark]);

  // Applied via OrbitControls' touch map rather than `.enabled`: the element's
  // own drag handler toggles `.enabled` around every joint drag, so a mode
  // implemented through `.enabled` gets silently reverted after the first drag.
  // touches.ONE is ours alone. -1 is "no action" (falls through the switch).
  useEffect(() => {
    const v = viewerRef.current;
    if (!v || !isCoarse) return;
    const touches = (v.controls as unknown as { touches?: { ONE: number } }).touches;
    if (touches) touches.ONE = touchMode === "camera" ? THREE.TOUCH.ROTATE : -1;
  }, [touchMode, isCoarse, status]);

  // Freeing the finger from OrbitControls is only half of it: urdf-loader's
  // PointerURDFDragControls listens for mousedown/mousemove/mouseup ONLY, and a
  // mobile browser synthesizes those from a tap, never from a drag. So on touch
  // there was no path to posing a joint at all. Drive the very same drag
  // controls from touch events here — same raycast, same setGrabbed/moveRay
  // calls the mouse handlers make, so highlighting, the manipulate-start/end
  // events and the OrbitControls lockout all behave identically.
  useEffect(() => {
    const v = viewerRef.current as
      | (URDFViewerElement & {
          renderer: THREE.WebGLRenderer;
          dragControls?: {
            manipulating: unknown;
            moveRay: (ray: THREE.Ray) => void;
            setGrabbed: (grabbed: boolean) => void;
          };
        })
      | null;
    if (!v || !isCoarse || status !== "ready") return;
    const drag = v.dragControls;
    const el = v.renderer?.domElement;
    if (!drag || !el) return;

    const raycaster = new THREE.Raycaster();
    const ndc = new THREE.Vector2();
    const aimAt = (t: Touch) => {
      const rect = el.getBoundingClientRect();
      ndc.x = ((t.clientX - rect.left) / rect.width) * 2 - 1;
      ndc.y = -((t.clientY - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(ndc, v.camera);
      drag.moveRay(raycaster.ray);
    };

    const onTouchStart = (e: TouchEvent) => {
      // Two fingers always mean the camera (pinch/pan), in either mode.
      if (touchModeRef.current !== "pose" || e.touches.length !== 1) return;
      aimAt(e.touches[0]);
      drag.setGrabbed(true);
      // Only swallow the gesture once a joint is actually grabbed, so a drag
      // that starts on empty background still scrolls the page.
      if (drag.manipulating) e.preventDefault();
    };
    const onTouchMove = (e: TouchEvent) => {
      if (!drag.manipulating || e.touches.length !== 1) return;
      e.preventDefault();
      aimAt(e.touches[0]);
    };
    const onTouchEnd = () => {
      if (drag.manipulating) drag.setGrabbed(false);
    };

    el.addEventListener("touchstart", onTouchStart, { passive: false });
    el.addEventListener("touchmove", onTouchMove, { passive: false });
    el.addEventListener("touchend", onTouchEnd);
    el.addEventListener("touchcancel", onTouchEnd);
    return () => {
      el.removeEventListener("touchstart", onTouchStart);
      el.removeEventListener("touchmove", onTouchMove);
      el.removeEventListener("touchend", onTouchEnd);
      el.removeEventListener("touchcancel", onTouchEnd);
    };
  }, [isCoarse, status]);

  // Flipping the toggle re-evaluates the current pose rather than waiting for
  // the next drag, so switching it on tells you about the pose you are looking
  // at now.
  useEffect(() => {
    const v = viewerRef.current;
    if (!v?.robot || !onCollisions) return;
    onCollisions(
      collisionCheck && collidersRef.current.length
        ? findCollisions(v.robot, collidersRef.current)
        : []
    );
  }, [collisionCheck, onCollisions]);

  // Sim mode. Gated on `status` because startSim needs the loaded robot: its
  // wheel geometry, its camera frames and its lift limits all come off the
  // model rather than out of a constants file.
  useEffect(() => {
    if (!sim || !prepared) return;
    const viewer = viewerRef.current;
    if (!viewer) return;
    const handle = startSim({
      viewer,
      keyLight: keyLightRef.current,
      grid: gridRef.current,
      invalidate: () => postRef.current?.invalidate(),
      setBloomEnabled: (on) => postRef.current?.setBloomEnabled(on),
      setSsaoEnabled: (on) => postRef.current?.setSsaoEnabled(on),
      setSsaoScale: (radius, range) => postRef.current?.setSsaoScale(radius, range),
      onState: (state) => simStateCb.current?.(state),
      initialCameraView: simViewRef.current ?? null,
    });
    simRef.current = handle;
    return () => {
      handle?.dispose();
      simRef.current = null;
    };
  }, [sim, prepared]);

  useEffect(() => {
    simRef.current?.setCameraView(simCameraView ?? null);
  }, [simCameraView]);

  const insetIndex = CAMERA_VIEWS.findIndex((v) => v.id === simCameraView);
  const insetLabel = insetIndex >= 0 ? CAMERA_VIEWS[insetIndex].label : null;
  const nextInset = CAMERA_VIEWS[(insetIndex + 1) % CAMERA_VIEWS.length];

  return (
    <div className={cn("relative", className)}>
      <div
        ref={containerRef}
        className={cn(
          "h-full w-full overflow-hidden bg-nori-hfffdf7",
          !frameless && "rounded-md border",
          // Display-only viewers must not eat pointer gestures (orbit-drag) or
          // let a drag start a text selection across the page.
          !interactive && "select-none [&_canvas]:pointer-events-none",
        )}
      />

      {/* The bezel around the robot's-eye inset. Drawn in HTML rather than
          WebGL because a border is a border; the rect comes from the same PIP
          constants the scissored render uses, so the two cannot drift.

          box-sizing is content-box on purpose: the WebGL rect is the CONTENT
          area, and the bezel has to sit entirely outside it (see PIP.bezelPx).
          With Tailwind's default border-box the border would eat into the image
          instead of framing it. */}
      {sim && status === "ready" && simCameraView && (
        <button
          type="button"
          onClick={() => onSimCameraViewChange?.(nextInset.id)}
          title={`Robot camera: ${insetLabel}. Click for ${nextInset.label}.`}
          className="group absolute cursor-pointer border-solid border-background shadow-soft transition-shadow hover:shadow-pop"
          style={{
            boxSizing: "content-box",
            top: PIP.marginPx - PIP.bezelPx,
            right: PIP.marginPx - PIP.bezelPx,
            width: `${PIP.widthFraction * 100}%`,
            aspectRatio: String(PIP.aspect),
            borderWidth: PIP.bezelPx,
            borderRadius: PIP.radiusPx,
          }}
        >
          {/* The image itself is WebGL underneath this element, so the button
              has no content of its own — only the label and the hover hint. */}
          <span className="pointer-events-none absolute bottom-1 left-1.5 rounded bg-background/85 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
            {insetLabel}
          </span>
          {/* Always visible, not hover-only: on a still image there is nothing
              to suggest the inset is clickable at all, and a hint you have to
              discover by hovering is a hint nobody finds. */}
          <span className="pointer-events-none absolute bottom-1 right-1.5 rounded bg-background/85 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-muted-foreground transition-colors group-hover:bg-background group-hover:text-ink">
            {nextInset.label} →
          </span>
        </button>
      )}

      {isCoarse && status === "ready" && (
        <div className="absolute bottom-3 left-3 z-10 flex overflow-hidden rounded-full border bg-background/90 text-sm font-medium shadow-sm backdrop-blur">
          {(
            [
              ["pose", "Pose joints"],
              ["camera", "Move camera"],
            ] as const
          ).map(([mode, label]) => (
            <button
              key={mode}
              type="button"
              onClick={() => setTouchMode(mode)}
              className={`px-3 py-1.5 ${
                touchMode === mode
                  ? "bg-nori-h8ab135/25 text-nori-h4d6a1e"
                  : "text-muted-foreground"
              }`}
            >
              {label}
            </button>
          ))}
        </div>
      )}

      {status === "loading" && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <p className="text-sm text-muted-foreground">Loading robot model…</p>
        </div>
      )}
      {status === "error" && (
        <div className="absolute inset-0 flex items-center justify-center p-4">
          <p className="text-sm text-destructive">Couldn't load the robot model.</p>
        </div>
      )}
    </div>
  );
};

export default RobotUrdfViewer;
