import React, { useContext, useEffect, useRef, useState } from "react";
import * as THREE from "three";

import URDFManipulator from "urdf-loader/src/urdf-manipulator-element.js";
import {
  createUrdfViewer,
  setupMeshLoader,
  URDFViewerElement,
} from "@/lib/urdfViewerHelpers";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import {
  attachPostProcessing,
  BLOOM_LAYER,
  type Post,
} from "@/nori/components/postprocess";
import {
  collectColliders,
  findCollisions,
  type Collider,
  type CollisionPair,
} from "@/nori/components/selfCollision";
import { ThemeProviderContext } from "@/contexts/ThemeContext";
import { cn } from "@/lib/utils";

if (typeof window !== "undefined" && !customElements.get("urdf-viewer")) {
  customElements.define("urdf-viewer", URDFManipulator);
}

/**
 * Renders the real Nori robot description.
 *
 * Deliberately NOT the upstream `UrdfViewer`: that one is bound to LeLab's
 * drag-and-drop context, defaults to the SO-101 arm, and opens a websocket for
 * live joint streaming. None of that applies to showing one fixed, shipped model.
 *
 * Presentation is matched to `nori/remote/Robot3D` (the stylised model on the
 * remote page) so the two read as the same robot: same palette, same lighting,
 * same long-lens low-angle framing. The palette below mirrors the constants in
 * packages/nori-sdk/src/robot-model.ts — if those change, change these.
 *
 * Assets are static files under `public/nori-urdf/`, generated by
 * `nori_ws/urdf_release/tools/sync_to_lelab.py`. Re-run it when the model changes.
 */

const URDF_PATH = "/nori-urdf/nori.urdf";

/**
 * Live lighting overrides from the URL, e.g.
 *   ?exposure=2.4&env=1.6&key=0.8
 *
 * Tuning a lighting chain by editing source, rebuilding and reloading is slow
 * enough that it turns into guesswork — especially when the composited and
 * uncomposited paths differ and you are trying to find the factor between them.
 * These make it one reload per value. They are read once at mount; absent
 * params keep the defaults below.
 */
function lightingOverrides() {
  const q =
    typeof window === "undefined"
      ? new URLSearchParams()
      : new URLSearchParams(window.location.search);
  const num = (k: string, fallback: number) => {
    const v = parseFloat(q.get(k) ?? "");
    return Number.isFinite(v) ? v : fallback;
  };
  return {
    exposure: num("exposure", 0.8),
    env: num("env", 0.2),
    key: num("key", 0.55),
    fill: num("fill", 0.12),
    eye: num("eye", 0.1),
  };
}

const HIGHLIGHT = "#a1d873"; // ARM_ACTIVE — the green a selected arm turns on the remote page

/**
 * Surface finish, from the description's own `materials.yaml` — the team's
 * render-validated PBR values (roughness / metallic per link), shipped alongside
 * the model as `materials.json` by sync_to_lelab.py.
 *
 * URDF carries colour and nothing else, so without this the viewer has to invent
 * surface properties. Colour still comes from the URDF <material> elements: those
 * include the stylised standin palette (white head, caps) that materials.yaml has
 * no opinion on, since it only describes the two real robot finishes.
 */
type Finish = { roughness: number; metalness: number };
const DEFAULT_FINISH: Finish = { roughness: 0.78, metalness: 0.06 };

type MaterialsDoc = {
  materials?: Record<string, { roughness?: number; metallic?: number }>;
  assign?: Record<string, string>;
};

/**
 * Per-link overrides applied ON TOP of materials.yaml.
 *
 * TEMPORARY. materials.yaml still describes the lift as foam-covered
 * (body_mat, roughness 0.9, metallic 0.0), which is stale — the lift is bare
 * metal now. The fix belongs in materials.yaml itself, since that file also feeds
 * the SDG renderer; this only stops the viewer showing something we know is wrong
 * in the meantime. DELETE THIS once materials.yaml is corrected.
 */
/**
 * Finishes keyed by URDF MATERIAL name, checked before anything link-based.
 *
 * materials.yaml binds finishes per link, which cannot express a link carrying
 * several surfaces — head_link alone is white shell, glass screen and lit eyes.
 * Material name is the finer-grained key, so it wins.
 */
const MATERIAL_FINISHES: Record<string, Finish> = {
  nori_screen: { roughness: 0.08, metalness: 0.85 }, // glossy display glass
  nori_eye: { roughness: 0.25, metalness: 0.1 },
};

const FINISH_OVERRIDES: Record<string, Finish> = {
  lift_bottom_link: { roughness: 0.24, metalness: 0.92 },
  lift_middle_link: { roughness: 0.24, metalness: 0.92 },
  lift_top_link: { roughness: 0.24, metalness: 0.92 },
};

function buildFinishLookup(
  doc: MaterialsDoc | null
): (link: string, material: string) => Finish {
  if (!doc?.materials || !doc?.assign)
    return (link: string, material: string) =>
      MATERIAL_FINISHES[material] ?? FINISH_OVERRIDES[link] ?? DEFAULT_FINISH;
  const finishFor = (matName: string | undefined): Finish => {
    const m = matName ? doc.materials?.[matName] : undefined;
    return m
      ? { roughness: m.roughness ?? DEFAULT_FINISH.roughness, metalness: m.metallic ?? 0 }
      : DEFAULT_FINISH;
  };
  const fallback = finishFor(doc.assign.default);
  return (link: string, material: string) =>
    MATERIAL_FINISHES[material] ??
    FINISH_OVERRIDES[link] ??
    (doc.assign?.[link] ? finishFor(doc.assign[link]) : fallback);
}

/**
 * The URDF addresses meshes as `package://nori_description/meshes/...`, a ROS
 * convention the browser knows nothing about. Rewrite to the static path they are
 * served from. The sync script fails if this prefix ever leaves the URDF, so the
 * two cannot silently drift.
 */
const rewriteMeshUrl = (url: string): string => {
  const marker = "nori_description/meshes/";
  const i = url.indexOf(marker);
  return i !== -1 ? `/nori-urdf/meshes/${url.slice(i + marker.length)}` : url;
};

/**
 * Recolour every mesh under the robot and frame the camera on it.
 *
 * Both have to wait for `urdf-processed`: before that the scene graph is empty,
 * so there are no materials to replace and the bounding box is degenerate — which
 * is exactly what made the default view start absurdly zoomed out (the element
 * ships a fov-75 camera parked at z=-10, i.e. ~8x the robot's height away).
 */
function styleAndFrame(
  viewer: URDFViewerElement,
  finishFor: (link: string, material: string) => Finish
) {
  const eyeIntensity = lightingOverrides().eye;
  const robot = viewer.robot;
  if (!robot) return;

  // Colour comes from the URDF's own <material> elements — the description is the
  // source of truth, so the model looks the same here, in RViz, and in Isaac.
  // urdf-loader builds those as MeshPhongMaterial, which renders plastic with a
  // hard specular hotspot; swap to Standard and keep the colour so dark parts read
  // as matte moulded plastic rather than polished ceramic.
  robot.traverse((obj: THREE.Object3D) => {
    const mesh = obj as THREE.Mesh;
    if (!mesh.isMesh) return;
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    // Walk up to the owning link: materials.yaml binds finishes by LINK name,
    // whereas the URDF binds colour by material name.
    let owner: THREE.Object3D | null = obj;
    while (owner && !/_link$/i.test(owner.name) && owner !== robot) owner = owner.parent;
    const olds = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
    const next = olds.map((m) => {
      const src = m as THREE.MeshPhongMaterial;
      const finish = finishFor(owner?.name ?? "", src?.name ?? "");
      const std = new THREE.MeshStandardMaterial({
        color: src?.color ? src.color.clone() : new THREE.Color(0xdee0e3),
        ...finish,
        transparent: src?.transparent ?? false,
        opacity: src?.opacity ?? 1,
        // Double-sided on purpose. The visual meshes are decimated OPEN shells
        // exported from CAD, and some exports carry whole patches wound inward
        // (elbow_pitch and forearm_yaw are measurably winding-inconsistent).
        // With default front-side culling an inward patch renders as a hole in
        // the part — invisible in mesh editors, which preview double-sided.
        // Backface cost on a ~150k-tri scene is negligible.
        side: THREE.DoubleSide,
      });
      // The eyes are the one thing on this robot that should look lit rather
      // than lit-upon. Emissive drives them past the bloom threshold (0.92) so
      // they glow, while nothing else on the model — not even the white shell —
      // gets near it.
      if (src?.name === "nori_eye") {
        std.emissive = new THREE.Color(0xdfefff);
        std.emissiveIntensity = eyeIntensity;
        std.toneMapped = true;
        // Opt this mesh into the bloom pass. Nothing else on the robot is on
        // this layer, so nothing else can glow however bright it renders.
        mesh.layers.enable(BLOOM_LAYER);
      }
      std.name = src?.name ?? "";
      return std;
    });
    mesh.material = next.length === 1 ? next[0] : next;
    // urdf-loader created the originals and nothing else references them.
    olds.forEach((m) => m?.dispose?.());
  });

  const box = new THREE.Box3().setFromObject(robot);
  if (box.isEmpty()) return;
  const size = new THREE.Vector3();
  const center = new THREE.Vector3();
  box.getSize(size);
  box.getCenter(center);

  // Long lens, matching Robot3D: a narrow fov flattens the perspective so the
  // robot doesn't bow outward at the edges of a small card.
  const camera = viewer.camera;
  camera.fov = 16;
  // Tight near/far, because SSAO reads the depth buffer.
  //
  // The default 0.01/100 is a 10,000:1 ratio, and depth precision is distributed
  // logarithmically — almost all of it lands in the first few centimetres, so at
  // robot distance neighbouring surfaces become indistinguishable. SSAO then
  // reads that noise as occlusion and darkens everything uniformly, which is
  // what made the composited image far darker than the raw one.
  //
  // A 1.3 m robot viewed from a few metres needs nothing like that range; 200:1
  // gives the depth buffer somewhere useful to spend its bits.
  camera.near = 0.05;
  camera.far = 20;

  // Distance that just contains the robot's largest dimension at this fov, plus
  // headroom so it isn't wedged against the edges.
  const extent = Math.max(size.x, size.y, size.z);
  const dist = (extent / 2 / Math.tan((camera.fov * Math.PI) / 180 / 2)) * 1.45;

  // Slightly off-axis and a touch below centre — the same gentle look-up as the
  // remote page, which reads better than a dead-on elevation.
  camera.position.set(
    center.x + dist * 0.62,
    center.y + size.y * 0.18,
    center.z + dist * 0.78
  );
  camera.updateProjectionMatrix();

  viewer.controls.target.copy(center);
  viewer.controls.update();
  viewer.redraw();
}

/**
 * Programmatic handle to the viewer, for choreographed sequences (the ?demo=1
 * release animation). Everything here goes through the same paths as user
 * interaction — setJoint fires the element's own angle-change event, so the
 * pose readout, mimic joints and collision check all react exactly as if a
 * person dragged the joint.
 */
export type ViewerApi = {
  setJoint: (name: string, value: number) => void;
  /** Green-highlight the link a joint drives, as hover does. Null clears. */
  highlightJoint: (name: string | null) => void;
  /** Place the camera on a sphere around the robot's centre. Radians, metres.
   *  targetYOffset raises the LOOK point without moving the orbit centre — the
   *  lift raises the robot ~0.5 m and a fixed target crops the head off. */
  orbit: (azimuth: number, elevation: number, distance: number, targetYOffset?: number) => void;
  frame: () => void;
};

/** What the viewer can tell the page about the part under the cursor. */
export type HoveredJoint = {
  name: string;
  type: string;
  lower?: number;
  upper?: number;
};

interface RobotUrdfViewerProps {
  className?: string;
  /** Fires with the joint under the cursor, or null when nothing is hovered. */
  onHoverJoint?: (joint: HoveredJoint | null) => void;
  /**
   * Fires whenever the pose changes with the links currently intersecting each
   * other. Kinematic only — geometry and joint limits, no physics.
   */
  onCollisions?: (pairs: CollisionPair[]) => void;
  /**
   * Run the self-collision check. Off by default: it is a diagnostic, not
   * something someone browsing the model asked for, and a red panel on a page
   * whose job is "here is our robot" reads as a fault rather than a feature.
   */
  collisionCheck?: boolean;
  /** Hands the page a programmatic handle once the model is ready. */
  onViewerReady?: (api: ViewerApi) => void;
  /** Fires once when the model loads, with every movable joint and its limits. */
  onJointsLoaded?: (joints: HoveredJoint[]) => void;
  /**
   * Fires with every joint's current value whenever the model is posed — on load,
   * and on each drag. With no robot connected this is the only pose information
   * available, so the page can show estimated angles and lift height from the
   * model itself rather than nothing at all.
   */
  onPoseChange?: (pose: Record<string, number>) => void;
}

const RobotUrdfViewer: React.FC<RobotUrdfViewerProps> = ({
  className,
  onHoverJoint,
  onPoseChange,
  onJointsLoaded,
  onCollisions,
  onViewerReady,
  collisionCheck = false,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewerRef = useRef<URDFViewerElement | null>(null);
  const { theme } = useContext(ThemeProviderContext);
  const isDark =
    theme === "dark" ||
    (theme === "system" &&
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);

  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");

  // Held in a ref so the mount effect can call the latest callback without
  // listing it as a dependency — depending on it would rebuild the viewer (and
  // refetch ~10 MB of meshes) whenever the parent re-renders.
  const hoverCb = useRef(onHoverJoint);
  hoverCb.current = onHoverJoint;
  const poseCb = useRef(onPoseChange);
  poseCb.current = onPoseChange;
  const jointsCb = useRef(onJointsLoaded);
  jointsCb.current = onJointsLoaded;
  const collisionCb = useRef(onCollisions);
  collisionCb.current = onCollisions;
  const checkOn = useRef(collisionCheck);
  checkOn.current = collisionCheck;
  const collidersRef = useRef<Collider[]>([]);
  const postRef = useRef<Post | null>(null);
  const readyCb = useRef(onViewerReady);
  readyCb.current = onViewerReady;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const viewer = createUrdfViewer(container, isDark);
    viewerRef.current = viewer;
    setupMeshLoader(viewer, rewriteMeshUrl);

    // createUrdfViewer paints an inline background; clear it so the Tailwind
    // `bg-nori-hf6f4eb` class below wins and the canvas tracks the theme token
    // the rest of the app uses.
    container.style.backgroundColor = "";

    // Joint hover highlight. createUrdfViewer sets LeLab's purple; Nori uses the
    // same green a selected arm turns on the remote page, so hovering here reads
    // as the same interaction.
    viewer.setAttribute("highlight-color", HIGHLIGHT);
    // The element's hover highlight SWAPS mesh materials for its own — which is
    // front-side by default. Every base material here is DoubleSide (the meshes
    // are open shells), so a single-sided highlight reintroduces the culling
    // holes exactly while a link is highlighted. Same for the demo highlight.
    const hl = (viewer as unknown as { highlightMaterial?: THREE.Material }).highlightMaterial;
    if (hl) hl.side = THREE.DoubleSide;

    // LIGHTING — deliberately rebuilt from nothing.
    //
    // Three parties add lights to this scene before we get here: the
    // urdf-viewer element (a HemisphereLight, and a DirectionalLight at
    // intensity Math.PI), and createUrdfViewer (an AmbientLight at 1.0 and a
    // DirectionalLight at 0.8). Stacked with an environment map that is itself
    // a full lighting solution, the model washes out — and muting them by
    // setting intensity to 0 leaves them in the graph to be re-enabled by
    // anything that walks it.
    //
    // So they are REMOVED, and exactly what is wanted is added back. If the
    // scene ever looks doubly-lit again, count the lights: there should be two.
    const preexisting: THREE.Object3D[] = [];
    viewer.scene.traverse((o: THREE.Object3D) => {
      if ((o as THREE.Light).isLight) preexisting.push(o);
    });
    preexisting.forEach((l) => l.removeFromParent());

    // The environment map carries the lighting; these two are supporting.
    //
    // The key is kept mainly for the SHADOW — a directional light is what casts
    // one, and an environment map alone leaves the robot floating with nothing
    // anchoring it to the floor. It is deliberately weak enough that the shading
    // is mostly image-based, so surfaces pick up tinted reflections rather than
    // flat white.
    //
    // Intensities are in three's physical units (r155+), where legacy 1.0 is
    // about Math.PI.
    const L = lightingOverrides();
    // Warm-white key/fill (~4500K). With the environment dialled low the
    // direct lights carry the shading, so their colour is what tints the model.
    const key = new THREE.DirectionalLight(0xffe9d2, L.key);
    key.position.set(4.0, 5.5, 3.0);
    // The element's own directional light was the shadow caster; removing it
    // above killed shadows entirely. A grounded contact shadow is the single
    // biggest thing separating "a render" from "a model floating in a void",
    // so the replacement key takes the job over. Tight ortho bounds keep the
    // shadow map's texels dense enough to stay crisp on a ~1.3 m robot.
    key.castShadow = true;
    key.shadow.mapSize.set(2048, 2048);
    const sc = key.shadow.camera as THREE.OrthographicCamera;
    sc.left = -1.6; sc.right = 1.6; sc.top = 1.6; sc.bottom = -1.6;
    sc.near = 0.1; sc.far = 14;
    key.shadow.bias = -0.0004;
    key.shadow.normalBias = 0.02;
    const fill = new THREE.DirectionalLight(0xfff1e0, L.fill);
    fill.position.set(-3.0, 1.5, 3.5);
    viewer.scene.add(key, fill);

    // Floor grid, matching the one on the remote page's model.
    //
    // NO rotation, deliberately. `up="Z"` does not make the scene Z-up: the
    // element rotates its inner `world` container instead (see _setUp), so the
    // scene itself stays three.js-default Y-up and GridHelper's native XZ plane
    // is already the ground. Rotating it stands the grid on its edge.
    // Image-based lighting. A single environment map does more for how machined
    // metal and moulded plastic read than any number of directional lights: it
    // gives every surface something to reflect. RoomEnvironment ships with
    // three, so this costs no download.
    const renderer = (viewer as unknown as { renderer?: THREE.WebGLRenderer }).renderer;
    if (renderer) {
      renderer.toneMapping = THREE.ACESFilmicToneMapping;
      // Exposure is the safe brightness dial. The pass order is
      //   scene -> TAA -> SSAO -> bloom -> OutputPass
      // and OutputPass is where tone mapping happens, so exposure is applied
      // AFTER bloom has already decided what glows. Raising it brightens the
      // image without pushing more pixels over the bloom threshold.
      //
      // environmentIntensity and the key light are the opposite: they run
      // before bloom, so raising those to brighten things brings the veiling
      // back. Reach for exposure first.
      renderer.toneMappingExposure = L.exposure;
      // Studio HDRI, downsampled to 512x256 from the 2k original. The map is
      // never drawn — it only lights — and PMREM convolves it heavily for the
      // diffuse and rough mips, so resolution beyond this buys nothing visible
      // while costing 6.1 MB instead of 512 KB. Downsampled in linear light, so
      // mean radiance is preserved to 0.36% (the RGBE mantissa, not the resize).
      const pmrem = new THREE.PMREMGenerator(renderer);
      pmrem.compileEquirectangularShader();

      // A procedural environment goes in immediately, then the HDRI replaces it
      // when it arrives. Two reasons: the model is never unlit (the direct
      // lights here are deliberately weak because IBL is meant to carry the
      // scene, so a missing environment reads as "everything is too dark"), and
      // a failed fetch degrades instead of silently removing the lighting —
      // which is indistinguishable from a tuning problem and wastes an
      // afternoon.
      viewer.scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
      viewer.redraw();

      new RGBELoader().load(
        "/env/studio_loft_512.hdr",
        (hdrTexture) => {
          hdrTexture.mapping = THREE.EquirectangularReflectionMapping;
          const prev = viewer.scene.environment;
          const baked = pmrem.fromEquirectangular(hdrTexture).texture;
          viewer.scene.environment = baked;
          // `?showenv=1` draws the environment as the background — the direct
          // answer to "is my HDRI even loading?". If you see the studio loft,
          // it is; if you see the flat page colour, it is not.
          if (new URLSearchParams(window.location.search).has("showenv")) {
            viewer.scene.background = baked;
          }
          prev?.dispose();
          hdrTexture.dispose();
          viewer.redraw();
          // Recorder gate: the demo capture must not start until the FINAL
          // environment is lit, or the video shows the fallback-to-HDRI tint
          // swap mid-take. Also set on error below so a failed fetch degrades
          // instead of deadlocking the recorder.
          (window as unknown as { __noriEnvReady?: boolean }).__noriEnvReady = true;
        },
        undefined,
        (err) => {
          // Loud on purpose: the fallback means the page still looks fine, so
          // nothing else would tell you the HDRI never loaded.
          console.error("[RobotUrdfViewer] environment map failed to load", err);
          (window as unknown as { __noriEnvReady?: boolean }).__noriEnvReady = true;
        }
      );
      // Reflections and fill, dialled well back — enough to give metal something
      // to reflect without lifting everything toward grey.
      // This is the colour dial, not just a brightness one. Direct lights are
      // white, so they only ever add white; the environment is what puts tinted
      // reflections on the metal and the gloss. Dropping it to compensate for
      // the earlier over-brightness is what made the model look grey — the fix
      // for "too bright" was removing the six redundant LIGHTS, not muting this.
      viewer.scene.environmentIntensity = L.env;
      // `environment` lights the scene; `background` is what you SEE.
      //
      // The background is painted EXPLICITLY rather than left transparent for
      // the container colour to show through. Once rendering is routed through
      // an EffectComposer the canvas is no longer composited over the page —
      // the passes write to opaque offscreen targets — so a null background
      // came out black. Reading the same theme token the container uses keeps
      // the two identical and flat.
      //
      // Still do NOT put the environment map here: it would fill the frame with
      // a photographic room.
      // The background rides through the same ACES tone mapping and exposure as
      // the robot, and ACES compresses AND desaturates midtones — at exposure
      // 0.8 a warm paper white comes out cool grey. So this is NOT the colour
      // that appears on screen: it is the pre-grade source, hand-tuned so the
      // graded result reads as warm paper next to the page's own hfffdf7
      // backdrop. The 1.35 factor is exposure headroom (fine in a HalfFloat
      // chain); ffedcf is the tuned hex. Change it via `?bg=<hex>`, judge by
      // eye, then bake the winner here.
      const bg = new THREE.Color(isDark ? "#262320" : "#ffedcf");
      const bgHex = new URLSearchParams(window.location.search).get("bg");
      if (bgHex && /^[0-9a-fA-F]{6}$/.test(bgHex)) bg.set(`#${bgHex}`);
      if (!isDark || bgHex) bg.multiplyScalar(1.35);
      viewer.scene.background = bg;
    }

    // Post-processing. Attached after the lights and environment so the passes
    // see the finished scene. TAA also replaces the MSAA that goes away the
    // moment rendering is routed through an offscreen target.
    // `?nopost=1` renders straight to the canvas with no composer. This exists
    // because "it looks too dark" has two completely different causes — the
    // lighting rig, or the passes subtracting from it — and they are impossible
    // to tell apart by eye when both are on. Compare the two and you know which
    // half to tune.
    const noPost =
      typeof window !== "undefined" &&
      new URLSearchParams(window.location.search).has("nopost");

    if (renderer && !noPost) {
      const rect = container.getBoundingClientRect();
      postRef.current = attachPostProcessing(
        renderer,
        viewer.scene,
        viewer.camera,
        { width: Math.max(1, rect.width), height: Math.max(1, rect.height) }
      );
      // Any camera move or pose change makes accumulated samples stale.
      viewer.controls.addEventListener?.("change", () => postRef.current?.invalidate());
      viewer.addEventListener("angle-change", () => postRef.current?.invalidate());
    }

    const grid = new THREE.GridHelper(3, 12, 0xcdc1a8, 0xccc4b6);
    // Invisible to raycasts. urdf-loader's PointerURDFDragControls raycasts the
    // WHOLE scene and takes intersections[0] — the nearest hit — so a floor plane
    // sitting in the scene wins the pick over much of the frame and joints stop
    // highlighting and dragging entirely. A no-op raycast keeps it decorative.
    grid.raycast = () => {};
    viewer.scene.add(grid);

    const onProcessed = () => {
      setStatus("ready");
      // One frame later: geometry is attached during this event, and the
      // bounding box is only correct once it has been.
      window.requestAnimationFrame(async () => {
        let doc: MaterialsDoc | null = null;
        try {
          const res = await fetch("/nori-urdf/materials.json");
          if (res.ok) doc = (await res.json()) as MaterialsDoc;
        } catch {
          /* fall back to DEFAULT_FINISH */
        }
        try {
          styleAndFrame(viewer, buildFinishLookup(doc));
          readPose();
          // Hide collision geometry and index it for the self-collision test.
          robotColliders(viewer);
          // Movable joints only: the model has 45 joints but most are fixed frames
          // (cameras, standin shells) with nothing to report.
          const joints = (viewer.robot as unknown as {
            joints?: Record<string, {
              jointType?: string; limit?: { lower?: number; upper?: number };
            }>;
          })?.joints;
          if (joints) {
            handOutApi(viewer);
            jointsCb.current?.(
              Object.entries(joints)
                .filter(([, j]) => j.jointType && j.jointType !== "fixed")
                .map(([name, j]) => ({
                  name,
                  type: j.jointType ?? "unknown",
                  lower: j.limit?.lower,
                  upper: j.limit?.upper,
                }))
            );
          }
        } catch {
          /* element may already be torn down */
        }
      });
    };
    const onError = () => setStatus("error");

    // urdf-loader emits the joint NAME; look the joint itself up on the robot for
    // its type and limits, which is what makes the readout worth showing.
    const onJointOver = (e: Event) => {
      const name = (e as CustomEvent<string>).detail;
      const j = (viewer.robot as unknown as { joints?: Record<string, {
        jointType?: string; limit?: { lower?: number; upper?: number };
      }> })?.joints?.[name];
      hoverCb.current?.({
        name,
        type: j?.jointType ?? "unknown",
        lower: j?.limit?.lower,
        upper: j?.limit?.upper,
      });
    };
    const onJointOut = () => hoverCb.current?.(null);

    const readPose = () => {
      const joints = (viewer.robot as unknown as {
        joints?: Record<string, { angle?: number; jointValue?: number[] }>;
      })?.joints;
      if (!joints) return;
      const pose: Record<string, number> = {};
      for (const [name, j] of Object.entries(joints)) {
        const v = typeof j.angle === "number" ? j.angle : j.jointValue?.[0];
        if (typeof v === "number") pose[name] = v;
      }
      poseCb.current?.(pose);
    };
    const onAngleChange = () => {
      readPose();
      runCollisionCheck(viewer);
    };

    const robotColliders = (v: URDFViewerElement) => {
      if (!v.robot) return;
      v.robot.traverse((o: THREE.Object3D) => {
        if ((o as unknown as { isURDFCollider?: boolean }).isURDFCollider) {
          o.visible = false;
        }
      });
      collidersRef.current = collectColliders(v.robot);
      runCollisionCheck(v);
    };

    // Same visual the manipulator uses on hover, driven programmatically. The
    // traversal rule matches the element's: colour every mesh under the joint,
    // stopping where a deeper movable joint begins.
    const demoHighlight = new THREE.MeshStandardMaterial({
      color: 0xa1d873,
      emissive: 0xa1d873,
      emissiveIntensity: 0.25,
      roughness: 0.6,
      side: THREE.DoubleSide, // matches the base materials — see note above
    });
    const highlighted = new Map<THREE.Mesh, THREE.Material | THREE.Material[]>();
    const clearHighlight = () => {
      highlighted.forEach((m, mesh) => (mesh.material = m));
      highlighted.clear();
    };
    const applyHighlight = (root: THREE.Object3D) => {
      const walk = (o: THREE.Object3D, isRoot: boolean) => {
        const j = o as unknown as { isURDFJoint?: boolean; jointType?: string };
        if (!isRoot && j.isURDFJoint && j.jointType !== "fixed") return;
        const mesh = o as THREE.Mesh;
        if (mesh.isMesh && !(o as unknown as { isURDFCollider?: boolean }).isURDFCollider) {
          if (!highlighted.has(mesh)) {
            highlighted.set(mesh, mesh.material);
            mesh.material = demoHighlight;
          }
        }
        o.children.forEach((c) => walk(c, false));
      };
      walk(root, true);
    };

    const handOutApi = (v: URDFViewerElement) => {
      const robot = v.robot as unknown as {
        joints?: Record<string, THREE.Object3D>;
      };
      readyCb.current?.({
        setJoint: (name, value) => v.setJointValue(name, value),
        highlightJoint: (name) => {
          clearHighlight();
          if (name && robot?.joints?.[name]) applyHighlight(robot.joints[name]);
          v.redraw();
          postRef.current?.invalidate();
        },
        orbit: (azimuth, elevation, distance, targetYOffset = 0) => {
          const t = v.controls.target.clone();
          t.y += targetYOffset;
          v.camera.position.set(
            t.x + distance * Math.cos(elevation) * Math.cos(azimuth),
            t.y + distance * Math.sin(elevation),
            t.z + distance * Math.cos(elevation) * Math.sin(azimuth)
          );
          v.camera.lookAt(t);
          v.controls.update();
          v.redraw();
          postRef.current?.invalidate();
        },
        frame: () => {
          v.redraw();
          postRef.current?.invalidate();
        },
      });
    };

    const runCollisionCheck = (v: URDFViewerElement) => {
      if (!v.robot || !collisionCb.current) return;
      if (!checkOn.current || collidersRef.current.length === 0) {
        collisionCb.current([]);
        return;
      }
      collisionCb.current(findCollisions(v.robot, collidersRef.current));
    };

    viewer.addEventListener("urdf-processed", onProcessed);
    viewer.addEventListener("error", onError);
    viewer.addEventListener("joint-mouseover", onJointOver);
    viewer.addEventListener("joint-mouseout", onJointOut);
    viewer.addEventListener("angle-change", onAngleChange);

    // `package` must be set even though the mesh loader rewrites full URLs:
    // urdf-loader consults it while resolving package:// before loadMeshFunc runs.
    // The viewer element always parses collision geometry (urdf-viewer-element
    // sets loader.parseCollision unconditionally) and hides it unless
    // `show-collision` is set — so the shapes are already in the scene, already
    // invisible, and just need indexing for the self-collision test.
    // Turns on the element's shadow-receiving ground plane, which it keeps
    // parked just under the robot's bounding box.
    viewer.setAttribute("display-shadow", "");
    viewer.setAttribute("package", "/");
    viewer.setAttribute("urdf", URDF_PATH);

    const onResize = () => {
      const r = container.getBoundingClientRect();
      postRef.current?.setSize(Math.max(1, r.width), Math.max(1, r.height));
      postRef.current?.invalidate();
    };
    const ro = new ResizeObserver(onResize);
    ro.observe(container);

    return () => {
      ro.disconnect();
      postRef.current?.dispose();
      postRef.current = null;
      viewer.removeEventListener("urdf-processed", onProcessed);
      viewer.removeEventListener("error", onError);
      viewer.removeEventListener("joint-mouseover", onJointOver);
      viewer.removeEventListener("joint-mouseout", onJointOut);
      viewer.removeEventListener("angle-change", onAngleChange);
      viewerRef.current = null;
      container.innerHTML = "";
    };
    // Theme is handled by the CSS class, so no rebuild on toggle — that would
    // refetch ~10 MB of meshes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Flipping the toggle re-evaluates the current pose rather than waiting for
  // the next drag, so switching it on tells you about the pose you are looking
  // at now.
  useEffect(() => {
    const v = viewerRef.current;
    if (!v?.robot || !onCollisions) return;
    onCollisions(
      collisionCheck && collidersRef.current.length
        ? findCollisions(v.robot, collidersRef.current)
        : []
    );
  }, [collisionCheck, onCollisions]);

  return (
    <div className={cn("relative", className)}>
      <div
        ref={containerRef}
        className="h-full w-full overflow-hidden rounded-md border bg-nori-hfffdf7"
      />

      {status === "loading" && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <p className="text-sm text-muted-foreground">Loading robot model…</p>
        </div>
      )}
      {status === "error" && (
        <div className="absolute inset-0 flex items-center justify-center p-4">
          <p className="text-sm text-destructive">Couldn't load the robot model.</p>
        </div>
      )}
    </div>
  );
};

export default RobotUrdfViewer;
