// Closed-form arm kinematics for the A3. PORTED 1:1 from the gateway's
// nori_gateway/arm_kinematics.py (branch vr-arm-kinematics, b2dcb56), which is
// the tested original; armKinematicsOracle.json pins this port against values
// generated by that Python so the two cannot drift silently.
//
// These are ROBOT FACTS -- link lengths, joint limits, the shape of the
// solution space. They are shared, not client policy. What the client owns is
// how it USES them (which swivel it prefers, how fast it lets the arm move),
// and that lives in the VR mapper, not here.
//
// Why this exists on the client at all: the gateway's task-cursor lane commands
// a TCP POSE and solves it on-board. The A3 wrist is NOT spherical -- 180 mm
// from wrist point to TCP -- so every wrist rotation swings the TCP and the
// on-board IK must move the whole arm to compensate, spending up to 52% of the
// arm's 344 mm reach holding the gripper still against the operator's own
// wrist. Measured on hardware 2026-09-07: orientation relaxations rose 5x per
// session and forward reach became impossible while the wrist stayed
// responsive. Solving the WRIST FIRST from anatomy and then placing the WRIST
// POINT removes the coupling entirely -- the client already knows the wrist
// angles when it places the arm, so there is nothing to compensate for.

export type Vec3 = [number, number, number];
export type ArmQ = [number, number, number, number];

// --- geometry, from nori_description/urdf (metres, radians) -----------------
const SHOULDER_PITCH_XYZ: Vec3 = [-2.2299999999988995e-06, 0.125, 0.08698265999999999];
const SHOULDER_PITCH_RPY: Vec3 = [0.0, 0.0, Math.PI];
const SHOULDER_ROLL_XYZ: Vec3 = [0.0, -0.0567, 0.0];
const SHOULDER_ROLL_RPY: Vec3 = [-Math.PI / 2, 0.0, 0.0];

export const UPPER_ARM_M = 0.18236;   // shoulder point -> elbow  (0.115 + 0.06736)
export const FOREARM_M = 0.16120;     // elbow -> wrist point     (0.115 + 0.0462)

/** The four joints this solver places, in chain order. */
export const SOLVED_JOINTS = [
  "shoulder_pitch", "shoulder_roll", "bicep_yaw", "elbow_pitch",
] as const;

const JOINT_LIMITS: [number, number][] = [
  [-Math.PI, Math.PI], [-1.6581, 1.6581],
  [-Math.PI, Math.PI], [-1.6581, 1.6581],
];

/** +1 for the left arm, -1 for the right. The right mirrors in Y exactly. */
export function sideSign(side: string): number {
  return String(side).startsWith("r") ? -1.0 : 1.0;
}

function wrap(a: number): number {
  let x = a;
  while (x > Math.PI) x -= 2 * Math.PI;
  while (x < -Math.PI) x += 2 * Math.PI;
  return x;
}

/**
 * Largest physical travel any joint must make between two configurations.
 *
 * NOT wrapped: shoulder_pitch and bicep_yaw are limited to exactly +/-pi, so a
 * joint cannot take the short way round. Measuring this with a wrap let a
 * 6.2 rad sweep through the continuity ceiling on hardware.
 */
export function jointDistance(a: readonly number[], b: readonly number[]): number {
  let m = 0;
  for (let i = 0; i < a.length; i++) m = Math.max(m, Math.abs(a[i] - b[i]));
  return m;
}

const rotX = (v: Vec3, t: number): Vec3 => {
  const c = Math.cos(t), s = Math.sin(t);
  return [v[0], c * v[1] - s * v[2], s * v[1] + c * v[2]];
};
const rotY = (v: Vec3, t: number): Vec3 => {
  const c = Math.cos(t), s = Math.sin(t);
  return [c * v[0] + s * v[2], v[1], -s * v[0] + c * v[2]];
};
const rotZ = (v: Vec3, t: number): Vec3 => {
  const c = Math.cos(t), s = Math.sin(t);
  return [c * v[0] - s * v[1], s * v[0] + c * v[1], v[2]];
};
const dot = (a: Vec3, b: Vec3) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];

/**
 * S, where the pitch and roll axes meet, in the arm-mount frame. Invariant in
 * q: the roll joint's origin sits ON the pitch axis, so q1 does not move it.
 */
export function shoulderPoint(sign = 1.0): Vec3 {
  const pitch: Vec3 = [SHOULDER_PITCH_XYZ[0], sign * SHOULDER_PITCH_XYZ[1], SHOULDER_PITCH_XYZ[2]];
  const roll: Vec3 = [SHOULDER_ROLL_XYZ[0], sign * SHOULDER_ROLL_XYZ[1], SHOULDER_ROLL_XYZ[2]];
  const p = rotZ(pitch, 0.0);
  const off = rotZ(rotX(roll, SHOULDER_PITCH_RPY[0]), SHOULDER_PITCH_RPY[2]);
  return [p[0] + off[0], p[1] + off[1], p[2] + off[2]];
}

/** Unit vector shoulder -> elbow. Mirroring negates u_x and u_y only. */
function shoulderDir(q1: number, q2: number, sign = 1.0): Vec3 {
  const s2 = Math.sin(q2), c2 = Math.cos(q2);
  return [sign * s2 * Math.sin(q1), sign * c2, -sign * s2 * Math.cos(q1)];
}

/**
 * COLUMNS of R_F2, the shoulder_roll frame's rotation. Returned as columns
 * because the caller wants R^T w, and column i dotted with w IS (R^T w)[i].
 * Getting this backwards produces a rotated solution that still looks
 * plausible -- it moved the FK round-trip from 1e-16 m to 0.3 m.
 */
function forearmFrame(q1: number, q2: number, sign = 1.0): [Vec3, Vec3, Vec3] {
  const col = (e: Vec3): Vec3 => {
    let v = rotX(e, q2 + sign * SHOULDER_ROLL_RPY[0]);
    v = rotY(v, q1);
    return rotZ(v, SHOULDER_PITCH_RPY[2]);
  };
  return [col([1, 0, 0]), col([0, 1, 0]), col([0, 0, 1])];
}

/**
 * Two unit vectors spanning the plane perpendicular to u. The reference leg
 * points DOWN as far as u allows, so swivel 0 is the elbow hanging at rest --
 * the pose a human arm defaults to, which makes 0 read as natural.
 */
function perpBasis(u: Vec3): [Vec3, Vec3] {
  let down: Vec3 = [0, 0, -1];
  if (Math.abs(dot(u, down)) > 0.98) down = [1, 0, 0];
  const d = dot(u, down);
  const raw: Vec3 = [down[0] - d * u[0], down[1] - d * u[1], down[2] - d * u[2]];
  const n = Math.hypot(raw[0], raw[1], raw[2]);
  const e1: Vec3 = [raw[0] / n, raw[1] / n, raw[2] / n];
  const e2: Vec3 = [
    u[1] * e1[2] - u[2] * e1[1],
    u[2] * e1[0] - u[0] * e1[2],
    u[0] * e1[1] - u[1] * e1[0],
  ];
  return [e1, e2];
}

/**
 * Elbow position for a wrist-point target and swivel, or null if out of reach.
 * The elbow lies on a circle about the shoulder->target axis; the swivel picks
 * a point on it. This is the arm's ONE redundant DOF.
 */
export function elbowPosition(target: Vec3, swivel: number, sign = 1.0): Vec3 | null {
  const S = shoulderPoint(sign);
  const dv: Vec3 = [target[0] - S[0], target[1] - S[1], target[2] - S[2]];
  const d = Math.hypot(dv[0], dv[1], dv[2]);
  if (d > UPPER_ARM_M + FOREARM_M || d < Math.abs(UPPER_ARM_M - FOREARM_M) || d < 1e-9) return null;
  const u: Vec3 = [dv[0] / d, dv[1] / d, dv[2] / d];
  const a = (UPPER_ARM_M * UPPER_ARM_M + d * d - FOREARM_M * FOREARM_M) / (2 * d);
  const r = Math.sqrt(Math.max(0.0, UPPER_ARM_M * UPPER_ARM_M - a * a));
  const C: Vec3 = [S[0] + a * u[0], S[1] + a * u[1], S[2] + a * u[2]];
  const [e1, e2] = perpBasis(u);
  const cs = Math.cos(swivel), sn = Math.sin(swivel);
  return [
    C[0] + r * (cs * e1[0] + sn * e2[0]),
    C[1] + r * (cs * e1[1] + sn * e2[1]),
    C[2] + r * (cs * e1[2] + sn * e2[2]),
  ];
}

/**
 * (q1, q2, q3, q4) placing the WRIST POINT at target, or null.
 *
 * Both halves have a mirror solution -- (q1+pi, -q2) and (q3+pi, -q4) reproduce
 * the same geometry -- giving four candidates. Most fall outside the URDF
 * limits; among the survivors the one NEAREST `seed` is returned, and that is
 * what makes consecutive calls continuous instead of hopping between mirror
 * configurations. Branch-hopping is exactly what KDL's random restarts did.
 */
export function solveWristPoint(
  target: Vec3, swivel = 0.0, seed: ArmQ | null = null, sign = 1.0,
): ArmQ | null {
  const E = elbowPosition(target, swivel, sign);
  if (E === null) return null;
  const S = shoulderPoint(sign);
  const u: Vec3 = [
    (E[0] - S[0]) / UPPER_ARM_M, (E[1] - S[1]) / UPPER_ARM_M, (E[2] - S[2]) / UPPER_ARM_M,
  ];
  const base2 = Math.acos(Math.max(-1, Math.min(1, sign * u[1])));
  const base1 = Math.atan2(sign * u[0], -sign * u[2]);
  const w: Vec3 = [target[0] - E[0], target[1] - E[1], target[2] - E[2]];
  let best: ArmQ | null = null;
  let bestCost: number | null = null;
  for (const [s1, s2] of [[base1, base2], [wrap(base1 + Math.PI), -base2]] as [number, number][]) {
    const cols = forearmFrame(s1, s2, sign);
    const v: Vec3 = [dot(cols[0], w), dot(cols[1], w), dot(cols[2], w)];
    const base4 = Math.acos(Math.max(-1, Math.min(1, -v[2] / FOREARM_M)));
    const base3 = Math.atan2(-v[1], -v[0]);
    for (const [s3, s4] of [[base3, base4], [wrap(base3 + Math.PI), -base4]] as [number, number][]) {
      const cand: ArmQ = [s1, s2, s3, s4];
      let ok = true;
      for (let i = 0; i < 4; i++) {
        if (!(JOINT_LIMITS[i][0] <= cand[i] && cand[i] <= JOINT_LIMITS[i][1])) { ok = false; break; }
      }
      if (!ok) continue;
      let cost = 0;
      if (seed !== null) for (let i = 0; i < 4; i++) cost += Math.abs(cand[i] - seed[i]);
      if (bestCost === null || cost < bestCost) { best = cand; bestCost = cost; }
    }
  }
  return best;
}

// --- swivel selection -------------------------------------------------------
// A FIXED swivel solves 37.7% of the reach sphere; searching solves 51.9%
// (measured 2026-09-04). Pinning it discards a quarter of the usable workspace,
// so the operator's elbow is a PREFERENCE, not a constraint. But an
// unconstrained search is its own bug: hopping the swivel by a search step moved
// joints up to 15 deg in one 2 mm frame. SwivelTracker rate-limits it.
const SWIVEL_SEARCH_STEP = (6.0 * Math.PI) / 180;
const SWIVEL_SEARCH_SPAN = Math.PI;
const SWIVEL_MAX_RATE = (90.0 * Math.PI) / 180;   // per second

// Per-tick joint-step ceiling. Closed form removes KDL's RANDOM flips but not
// the arm's own SINGULARITIES: when the elbow straightens, bicep_yaw stops
// affecting the wrist point and becomes undefined. Measured over 13205 samples
// at 2 mm steps: median 0.76 deg, p90 2.28 deg -- but p99 62.9 deg and a worst
// case of 168 deg. So an exact, deterministic solution can still be unusable.
// Rather than damp the ill-conditioned joint (trading a flip for a position
// error the operator cannot see), the solver REFUSES a step it cannot take
// smoothly and the caller holds. The operator steers around the singularity,
// which is what they would do with their own arm.
export const MAX_JOINT_SPEED_RAD_S = 2.0;

/** Smoothed swivel state. Call solve() once per control tick. */
export class SwivelTracker {
  value: number;
  sign: number;
  /** Set when solve() refuses: the smallest joint jump any candidate needed. */
  blockedBy: number | null = null;

  constructor(initial = 0.0, sign = 1.0) {
    this.value = initial;
    this.sign = sign;
  }

  reset(value = 0.0) { this.value = value; }

  /**
   * Best (joints, swivel) for this tick, or null if nothing solves. Tries the
   * rate-limited swivel first, then walks outward. The result is latched, so
   * the next tick starts where this one ended rather than snapping back to
   * `preferred` and re-hopping.
   */
  solve(
    target: Vec3, preferred: number, dt: number, seed: ArmQ | null = null,
  ): { q: ArmQ; swivel: number } | null {
    const limit = SWIVEL_MAX_RATE * Math.max(dt, 0.0);
    const step = Math.max(-limit, Math.min(limit, wrap(preferred - this.value)));
    const wanted = wrap(this.value + step);
    const candidates = [wanted];
    const n = Math.trunc(SWIVEL_SEARCH_SPAN / SWIVEL_SEARCH_STEP);
    for (let i = 1; i <= n; i++) {
      candidates.push(wrap(wanted + i * SWIVEL_SEARCH_STEP));
      candidates.push(wrap(wanted - i * SWIVEL_SEARCH_STEP));
    }
    const ceiling = MAX_JOINT_SPEED_RAD_S * Math.max(dt, 1e-3);
    let fallback: number | null = null;
    for (const psi of candidates) {
      const q = solveWristPoint(target, psi, seed, this.sign);
      if (q === null) continue;
      if (seed === null) { this.value = psi; this.blockedBy = null; return { q, swivel: psi }; }
      const jump = jointDistance(q, seed);
      if (jump <= ceiling) { this.value = psi; this.blockedBy = null; return { q, swivel: psi }; }
      if (fallback === null) fallback = jump;
    }
    this.blockedBy = fallback;
    return null;
  }
}

// --- forward direction ------------------------------------------------------

/** Elbow position for the first two joints. Independent of q3 -- the property
 *  that makes the shoulder effectively spherical. */
export function elbowPoint(q1: number, q2: number, sign = 1.0): Vec3 {
  const S = shoulderPoint(sign);
  const u = shoulderDir(q1, q2, sign);
  return [S[0] + UPPER_ARM_M * u[0], S[1] + UPPER_ARM_M * u[1], S[2] + UPPER_ARM_M * u[2]];
}

/** Wrist-point position for the four solved joints. Independent of the three
 *  wrist joints, which is what lets the operator drive them freely. */
export function wristPoint(
  q1: number, q2: number, q3: number, q4: number, sign = 1.0,
): Vec3 {
  const E = elbowPoint(q1, q2, sign);
  const s4 = Math.sin(q4), c4 = Math.cos(q4);
  const v: Vec3 = [
    -FOREARM_M * s4 * Math.cos(q3),
    -FOREARM_M * s4 * Math.sin(q3),
    -FOREARM_M * c4,
  ];
  const cols = forearmFrame(q1, q2, sign);
  const out: Vec3 = [0, 0, 0];
  for (let i = 0; i < 3; i++) {
    out[i] = E[i] + cols[0][i] * v[0] + cols[1][i] * v[1] + cols[2][i] * v[2];
  }
  return out;
}

/** The swivel angle a configuration is already in. Seeding SwivelTracker with
 *  this keeps the elbow where it is instead of snapping to a nominal swivel the
 *  instant the operator squeezes the clutch. */
export function swivelOf(q: ArmQ, sign = 1.0): number {
  const S = shoulderPoint(sign);
  const E = elbowPoint(q[0], q[1], sign);
  const P = wristPoint(q[0], q[1], q[2], q[3], sign);
  const dv: Vec3 = [P[0] - S[0], P[1] - S[1], P[2] - S[2]];
  const d = Math.hypot(dv[0], dv[1], dv[2]);
  if (d < 1e-9) return 0.0;
  const u: Vec3 = [dv[0] / d, dv[1] / d, dv[2] / d];
  const a = (UPPER_ARM_M * UPPER_ARM_M + d * d - FOREARM_M * FOREARM_M) / (2 * d);
  const C: Vec3 = [S[0] + a * u[0], S[1] + a * u[1], S[2] + a * u[2]];
  const w: Vec3 = [E[0] - C[0], E[1] - C[1], E[2] - C[2]];
  const [e1, e2] = perpBasis(u);
  return Math.atan2(dot(w, e2), dot(w, e1));
}
